/**
 * Flower and leaf artwork for the Stress Reliefer's bloom effects.
 *
 * 146 PNGs pulled from the Icons8 catalogue (icons8.com) via its MCP
 * server: every flower and leaf Icons8 draws, in every one of its art styles
 * that reads as an actual plant — the neon, pixel, sticker-border and
 * baked-drop-shadow styles were dropped, because a burst is only convincing if
 * nothing in it looks like a UI glyph. Each file is cropped to its own alpha
 * bounding box so the artwork fills the particle: untrimmed padding renders a
 * 40px bloom at 28px, and spins it around the padding's centre instead of the
 * flower's.
 *
 * Generated — see the fetch script in the PR description. Icons8 assets carry
 * Icons8's licence; keep the attribution in the app's credits.
 */

/** Front-facing blooms. These read as a flower LOOKING AT YOU, so they may only
 *  ever be rotated in the plane — a rotateX/rotateY on one of these reads as the
 *  flower being squashed, not as a petal turning. */
export const BLOOM_FLOWERS: readonly string[] = [
  '/blooms/flowers/blossom--emoji.png',
  '/blooms/flowers/bridal-bouquet--color.png',
  '/blooms/flowers/bunch-flowers--color.png',
  '/blooms/flowers/bunch-flowers--cotton.png',
  '/blooms/flowers/bunch-flowers--fluent.png',
  '/blooms/flowers/bunch-flowers--papercut.png',
  '/blooms/flowers/bunch-flowers--plasticine.png',
  '/blooms/flowers/cotton--color.png',
  '/blooms/flowers/cotton--dusk.png',
  '/blooms/flowers/cotton--fluent.png',
  '/blooms/flowers/dandelion--color.png',
  '/blooms/flowers/dandelion--fluent.png',
  '/blooms/flowers/flower--color.png',
  '/blooms/flowers/flower--deco-color.png',
  '/blooms/flowers/flower--dusk.png',
  '/blooms/flowers/flower--fluent.png',
  '/blooms/flowers/flower--pieces.png',
  '/blooms/flowers/flower--plasticine.png',
  '/blooms/flowers/flower-doodle--color.png',
  '/blooms/flowers/flower-doodle--dusk.png',
  '/blooms/flowers/flower-doodle--fluent.png',
  '/blooms/flowers/flower-doodle--plasticine.png',
  '/blooms/flowers/geometric-flowers--color.png',
  '/blooms/flowers/geometric-flowers--dusk.png',
  '/blooms/flowers/geometric-flowers--fluent.png',
  '/blooms/flowers/hibiscus--emoji.png',
  '/blooms/flowers/lavender--color.png',
  '/blooms/flowers/lavender--fluent.png',
  '/blooms/flowers/lavender--pieces.png',
  '/blooms/flowers/lotus--color.png',
  '/blooms/flowers/lotus--cotton.png',
  '/blooms/flowers/lotus--deco-color.png',
  '/blooms/flowers/lotus--fluent.png',
  '/blooms/flowers/lotus--pieces.png',
  '/blooms/flowers/lotus--plasticine.png',
  '/blooms/flowers/lotus-v2--cotton.png',
  '/blooms/flowers/protea-flower--color.png',
  '/blooms/flowers/rose--color.png',
  '/blooms/flowers/rose--deco-color.png',
  '/blooms/flowers/rose--fluent.png',
  '/blooms/flowers/rose--plasticine.png',
  '/blooms/flowers/rose-bouquet--color.png',
  '/blooms/flowers/sakura--color.png',
  '/blooms/flowers/sakura--deco-color.png',
  '/blooms/flowers/sakura--fluent.png',
  '/blooms/flowers/sakura--papercut.png',
  '/blooms/flowers/spa-flower--color.png',
  '/blooms/flowers/spa-flower--deco-color.png',
  '/blooms/flowers/spa-flower--dusk.png',
  '/blooms/flowers/spa-flower--fluent.png',
  '/blooms/flowers/spa-flower--lollipop.png',
  '/blooms/flowers/spa-flower--papercut.png',
  '/blooms/flowers/spa-flower--pieces.png',
  '/blooms/flowers/spa-flower--plasticine.png',
  '/blooms/flowers/spring--color.png',
  '/blooms/flowers/spring--deco-color.png',
  '/blooms/flowers/spring--dusk.png',
  '/blooms/flowers/spring--fluent.png',
  '/blooms/flowers/spring--lollipop.png',
  '/blooms/flowers/spring--papercut.png',
  '/blooms/flowers/spring--plasticine.png',
  '/blooms/flowers/sunflower--color.png',
  '/blooms/flowers/sunflower--dusk.png',
  '/blooms/flowers/sunflower--fluent.png',
  '/blooms/flowers/sunflower--pieces.png',
  '/blooms/flowers/sunflower--plasticine.png',
  '/blooms/flowers/trillium--color.png',
  '/blooms/flowers/trillium--dusk.png',
  '/blooms/flowers/trillium--fluent.png',
  '/blooms/flowers/trillium--pieces.png',
  '/blooms/flowers/trillium--plasticine.png',
  '/blooms/flowers/tudor-rose--color.png',
  '/blooms/flowers/violet-flower--color.png',
];

/** Leaves and sprigs. Unlike the blooms these are flat blades, so they CAN be
 *  tumbled in 3D — an edge-on leaf is exactly what a falling leaf does. */
export const BLOOM_LEAVES: readonly string[] = [
  '/blooms/leaves/autumn--color.png',
  '/blooms/leaves/autumn--deco-color.png',
  '/blooms/leaves/autumn--fluent.png',
  '/blooms/leaves/autumn--papercut.png',
  '/blooms/leaves/autumn--pieces.png',
  '/blooms/leaves/autumn--plasticine.png',
  '/blooms/leaves/basil--color.png',
  '/blooms/leaves/basil--fluent.png',
  '/blooms/leaves/basil--plasticine.png',
  '/blooms/leaves/bay-leaf--color.png',
  '/blooms/leaves/bay-leaf--fluent.png',
  '/blooms/leaves/chard--color.png',
  '/blooms/leaves/chard--dusk.png',
  '/blooms/leaves/chard--fluent.png',
  '/blooms/leaves/chard--plasticine.png',
  '/blooms/leaves/clover--color.png',
  '/blooms/leaves/clover--deco-color.png',
  '/blooms/leaves/clover--fluent.png',
  '/blooms/leaves/clover--papercut.png',
  '/blooms/leaves/clover--plasticine.png',
  '/blooms/leaves/collard-greens--color.png',
  '/blooms/leaves/collard-greens--dusk.png',
  '/blooms/leaves/collard-greens--fluent.png',
  '/blooms/leaves/collard-greens--plasticine.png',
  '/blooms/leaves/grass--color.png',
  '/blooms/leaves/grass--fluent.png',
  '/blooms/leaves/grass--papercut.png',
  '/blooms/leaves/grass--pieces.png',
  '/blooms/leaves/kale--color.png',
  '/blooms/leaves/kale--dusk.png',
  '/blooms/leaves/kale--plasticine.png',
  '/blooms/leaves/leaf--color.png',
  '/blooms/leaves/leaf--deco-color.png',
  '/blooms/leaves/leaf--dusk.png',
  '/blooms/leaves/leaf--emoji.png',
  '/blooms/leaves/leaf--fluent.png',
  '/blooms/leaves/leaf--plasticine.png',
  '/blooms/leaves/maple-leaf--color.png',
  '/blooms/leaves/maple-leaf--deco-color.png',
  '/blooms/leaves/maple-leaf--dusk.png',
  '/blooms/leaves/maple-leaf--fluent.png',
  '/blooms/leaves/maple-leaf--papercut.png',
  '/blooms/leaves/maple-leaf--plasticine.png',
  '/blooms/leaves/mint--color.png',
  '/blooms/leaves/mint--dusk.png',
  '/blooms/leaves/mint--plasticine.png',
  '/blooms/leaves/natural-food--color.png',
  '/blooms/leaves/natural-food--deco-color.png',
  '/blooms/leaves/natural-food--dusk.png',
  '/blooms/leaves/natural-food--emoji.png',
  '/blooms/leaves/natural-food--fluent.png',
  '/blooms/leaves/natural-food--papercut.png',
  '/blooms/leaves/natural-food--plasticine.png',
  '/blooms/leaves/oak-leaf--color.png',
  '/blooms/leaves/oak-leaf--fluent.png',
  '/blooms/leaves/oak-leaf--plasticine.png',
  '/blooms/leaves/parsley--color.png',
  '/blooms/leaves/parsley--fluent.png',
  '/blooms/leaves/pussy-willow--color.png',
  '/blooms/leaves/spinach--color.png',
  '/blooms/leaves/spinach--deco-color.png',
  '/blooms/leaves/spinach--dusk.png',
  '/blooms/leaves/spinach--fluent.png',
  '/blooms/leaves/spinach--papercut.png',
  '/blooms/leaves/spinach--plasticine.png',
  '/blooms/leaves/three-leaf-clover--color.png',
  '/blooms/leaves/three-leaf-clover--fluent.png',
  '/blooms/leaves/three-leaf-clover--papercut.png',
  '/blooms/leaves/three-leaf-clover--plasticine.png',
  '/blooms/leaves/thyme--color.png',
  '/blooms/leaves/thyme--dusk.png',
  '/blooms/leaves/thyme--fluent.png',
  '/blooms/leaves/thyme--plasticine.png',
];

export const BLOOM_ALL: readonly string[] = [...BLOOM_FLOWERS, ...BLOOM_LEAVES];
