/**
 * The Canvas Resident's sprite sheet.
 *
 * Every pose is hand-authored pixel art on a fixed 40x32 grid, stored as one
 * character per pixel. Nothing here is computed from the simulation — which is
 * the whole point. The previous cat drew itself from raw fillRect calls at
 * fractional coordinates, so legs changed height mid-stride and the silhouette
 * tore apart at certain zooms. Baked frames can't stretch, can't tear, and a
 * walk cycle either reads as a cat or it doesn't while you're still drawing it.
 *
 * Character legend:
 *   .  transparent      K  body            S  shade (far limbs, depth)
 *   B  belly            E  eye white       P  pupil (drawn at runtime, so the
 *   N  nose             I  inner ear          cat can look at your cursor)
 *   w  light detail — whiskers, closed-eye lines, the seam between two
 *      overlapping forms. Deliberately NOT part of the silhouette, so it
 *      never grows an outline of its own.
 *
 * The outline is never authored. It's dilated from the silhouette at compile
 * time, which means it is always sealed and always exactly one pixel — the
 * single detail that separates "desktop companion" from "blob with ears".
 */

export interface CoatPalette {
  name: string;
  body: string;
  shade: string;
  belly: string;
  outline: string;
  eye: string;
  pupil: string;
  nose: string;
  earInner: string;
  detail: string;
}

/** Midnight is index 0 and heavily favoured — it's the cat this was drawn for. */
/**
 * One coat. The cat is orange — that was the call, and carrying four unused
 * palettes "just in case" is how a sprite compiler ends up with dead branches
 * nobody has looked at in months. The structure stays per-coat so a second one
 * is a one-line addition if it's ever actually wanted.
 */
export const COATS: CoatPalette[] = [
  {
    name: 'ginger',
    body: '#D97B2E',      // warm mid-orange, reads on light and dark boards
    shade: '#B25F1E',     // far limbs sit behind the near pair
    belly: '#F6DCB4',
    outline: '#FFF4E4',
    eye: '#FFFFFF',
    pupil: '#2A1A0E',
    nose: '#C4544E',
    earInner: '#B0604F',
    detail: '#FFF4E4',
  },
];

export const ART_W = 40;
export const ART_H = 32;
export const ART_GROUND = 30;

export const FRAME_ART: Record<string, { anchorX: number; rows: string[] }> = {
  sit0: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '...............K.........K..............',
    '...............K.........K..............',
    '..............KIK.......KIK.............',
    '..............KIK.......KIK.............',
    '.............KKIKK.KKK.KKIKK............',
    '.............KKIKKKKKKKKKIKK............',
    '............KKIIIKKKKKKKIIIKK...........',
    '............KKKKKKKKKKKKKKKKK...........',
    '............KKKEPEKKKKKEPEKKK...........',
    '........www.KKKEPEKKKKKEPEKKKwww........',
    '...........KKKKEEEKKKKKEEEKKKK..........',
    '.........ww.KKKKKKKKKKKKKKKKKww.........',
    '............KKKKKKKKNKKKKKKKK...........',
    '.............KKKKKKNKNKKKKKK............',
    '..............KKKKKKKKKKKKK.............',
    '...............KKKKKKKKKKK..............',
    '..............KKKKKKKKKKKKK.............',
    '..............KKKKKKKKKKKKK....K........',
    '..............KKKKKKKKKKKKK...KKKK......',
    '..............KKKKKKKKKKKKK....KKKK.....',
    '.............KKKKKKKKKKKKKKK.....KKK....',
    '............KKKKKKKKKKKKKKKKK.....KK....',
    '............KKKKKKKKKKKKKKKKK.....KK....',
    '...........KKKKKKKKKKKKKKKKKKK...KKK....',
    '...........KKKKKKKKKKKKKKKKKKK.KKKK.....',
    '...........KKKKKKKKKKKKKKKKKKKKKKKK.....',
    '...........KKKKKKKKKwKKKKKKKKKKKK.......',
    '...........KKKKKKKKKwKKKKKKKKKK.........',
    '............KKKKKKKKwKKKKKKKK...........',
    '...................KKK..................',
  ] },
  sit1: { anchorX: 20, rows: [
    '........................................',
    '...............K.........K..............',
    '...............K.........K..............',
    '..............KIK.......KIK.............',
    '..............KIK.......KIK.............',
    '.............KKIKK.KKK.KKIKK............',
    '.............KKIKKKKKKKKKIKK............',
    '............KKIIIKKKKKKKIIIKK...........',
    '............KKKKKKKKKKKKKKKKK...........',
    '............KKKEPEKKKKKEPEKKK...........',
    '........www.KKKEPEKKKKKEPEKKKwww........',
    '...........KKKKEEEKKKKKEEEKKKK..........',
    '.........ww.KKKKKKKKKKKKKKKKKww.........',
    '............KKKKKKKKNKKKKKKKK...........',
    '.............KKKKKKNKNKKKKKK............',
    '..............KKKKKKKKKKKKK.............',
    '...............KKKKKKKKKKK..............',
    '..............KKKKKKKKKKKKK.............',
    '..............KKKKKKKKKKKKK.............',
    '..............KKKKKKKKKKKKK....K........',
    '..............KKKKKKKKKKKKK...KKKK......',
    '..............KKKKKKKKKKKKK....KKKK.....',
    '.............KKKKKKKKKKKKKKK.....KKK....',
    '............KKKKKKKKKKKKKKKKK.....KK....',
    '............KKKKKKKKKKKKKKKKK.....KK....',
    '...........KKKKKKKKKKKKKKKKKKK...KKK....',
    '...........KKKKKKKKKKKKKKKKKKK.KKKK.....',
    '...........KKKKKKKKKKKKKKKKKKKKKKKK.....',
    '...........KKKKKKKKKwKKKKKKKKKKKK.......',
    '...........KKKKKKKKKwKKKKKKKKKK.........',
    '............KKKKKKKKwKKKKKKKK...........',
    '...................KKK..................',
  ] },
  sit0e: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '...............K........................',
    '...............K........................',
    '..............KIK.......................',
    '..............KIK.......................',
    '.............KKIKK.KKK..................',
    '.............KKIKKKKKKKKKKKKK...........',
    '............KKIIIKKKKKKKKKKKK...........',
    '............KKKKKKKKKKKKKKKK............',
    '............KKKEPEKKKKKEPEKKK...........',
    '........www.KKKEPEKKKKKEPEKKKwww........',
    '...........KKKKEEEKKKKKEEEKKKK..........',
    '.........ww.KKKKKKKKKKKKKKKKKww.........',
    '............KKKKKKKKNKKKKKKKK...........',
    '.............KKKKKKNKNKKKKKK............',
    '..............KKKKKKKKKKKKK.............',
    '...............KKKKKKKKKKK..............',
    '..............KKKKKKKKKKKKK.............',
    '..............KKKKKKKKKKKKK....K........',
    '..............KKKKKKKKKKKKK...KKKK......',
    '..............KKKKKKKKKKKKK....KKKK.....',
    '.............KKKKKKKKKKKKKKK.....KKK....',
    '............KKKKKKKKKKKKKKKKK.....KK....',
    '............KKKKKKKKKKKKKKKKK.....KK....',
    '...........KKKKKKKKKKKKKKKKKKK...KKK....',
    '...........KKKKKKKKKKKKKKKKKKK.KKKK.....',
    '...........KKKKKKKKKKKKKKKKKKKKKKKK.....',
    '...........KKKKKKKKKwKKKKKKKKKKKK.......',
    '...........KKKKKKKKKwKKKKKKKKKK.........',
    '............KKKKKKKKwKKKKKKKK...........',
    '...................KKK..................',
  ] },
  sit1e: { anchorX: 20, rows: [
    '........................................',
    '...............K........................',
    '...............K........................',
    '..............KIK.......................',
    '..............KIK.......................',
    '.............KKIKK.KKK..................',
    '.............KKIKKKKKKKKKKKKK...........',
    '............KKIIIKKKKKKKKKKKK...........',
    '............KKKKKKKKKKKKKKKK............',
    '............KKKEPEKKKKKEPEKKK...........',
    '........www.KKKEPEKKKKKEPEKKKwww........',
    '...........KKKKEEEKKKKKEEEKKKK..........',
    '.........ww.KKKKKKKKKKKKKKKKKww.........',
    '............KKKKKKKKNKKKKKKKK...........',
    '.............KKKKKKNKNKKKKKK............',
    '..............KKKKKKKKKKKKK.............',
    '...............KKKKKKKKKKK..............',
    '..............KKKKKKKKKKKKK.............',
    '..............KKKKKKKKKKKKK.............',
    '..............KKKKKKKKKKKKK....K........',
    '..............KKKKKKKKKKKKK...KKKK......',
    '..............KKKKKKKKKKKKK....KKKK.....',
    '.............KKKKKKKKKKKKKKK.....KKK....',
    '............KKKKKKKKKKKKKKKKK.....KK....',
    '............KKKKKKKKKKKKKKKKK.....KK....',
    '...........KKKKKKKKKKKKKKKKKKK...KKK....',
    '...........KKKKKKKKKKKKKKKKKKK.KKKK.....',
    '...........KKKKKKKKKKKKKKKKKKKKKKKK.....',
    '...........KKKKKKKKKwKKKKKKKKKKKK.......',
    '...........KKKKKKKKKwKKKKKKKKKK.........',
    '............KKKKKKKKwKKKKKKKK...........',
    '...................KKK..................',
  ] },
  groom0: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '...............K.........K..............',
    '...............K.........K..............',
    '..............KIK.......KIK.............',
    '..............KIK.......KIK.............',
    '.............KKIKK.KKK.KKIKK............',
    '.............KKIKKKKKKKKKIKK............',
    '............KKIIIKKKKKKKIIIKK...........',
    '............KKKKKKKKKKKKKKKKK...........',
    '............KKKKKKKKKKKKKKKKK...........',
    '........www.KKKwwwKKKKKwwwKKKwww........',
    '...........KKKKKKKKKKKKKKKKKKK..........',
    '.........ww.KKKKKKKKKKKKKKKKKww.........',
    '............KKKKKKKKNKKKKKKKK...........',
    '.............KKKKKKNKNKKKKKK............',
    '..............KKKKKKKKKKKKK....K........',
    '..............KKKKKKKKKKKKK...KKKK......',
    '..............KKKKKKKKKKKKK....KKKK.....',
    '.............KKKKKKKKKKKKKKK.....KKK....',
    '............KKKKKKKKKKKKKKKKK.....KK....',
    '............KKKKKKKKKKKKKKKKK.....KK....',
    '...........KKKKKKKKKKKKKKKKKKK...KKK....',
    '...........KKKKKKKKKKKKKKKKKKK.KKKK.....',
    '...........KKKKKKKKKKKKKKKKKKKKKKKK.....',
    '...........KKKKKKKKKwKKKKKKKKKKKK.......',
    '...........KKKKKKKKKwKKKKKKKKKK.........',
    '............KKKKKKKKwKKKKKKKK...........',
    '...................KKK..................',
  ] },
  groom1: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '...............K.........K..............',
    '...............K.........K..............',
    '..............KIK.......KIK.............',
    '..............KIK.......KIK.............',
    '.............KKIKK.KKK.KKIKK............',
    '.............KKIKKKKKKKKKIKK............',
    '............KKIIIKKKKKKKIIIKK...........',
    '............KKKKKKKKKKKKKKKKK...........',
    '............KKKKKKKKKKKKKKKKK...........',
    '........www.KKKwwwKKKKKwwwKKKwww........',
    '...........KKKKKKKKKKKKKKKKKKK..........',
    '.........ww.KKKKKKKKKKKKKKKKKww.........',
    '............KKKKKKKKNKKKKKKKK...........',
    '.............KKKKKKNKNKKKKKK...K........',
    '..............KKKKKKKKKKKKK...KKKK......',
    '..............KKKKKKKKKKKKK....KKKK.....',
    '.............KKKKKKKKKKKKKKK.....KKK....',
    '............KKKKKKKKKKKKKKKKK.....KK....',
    '............KKKKKKKKKKKKKKKKK.....KK....',
    '...........KKKKKKKKKKKKKKKKKKK...KKK....',
    '...........KKKKKKKKKKKKKKKKKKK.KKKK.....',
    '...........KKKKKKKKKKKKKKKKKKKKKKKK.....',
    '...........KKKKKKKKKwKKKKKKKKKKKK.......',
    '...........KKKKKKKKKwKKKKKKKKKK.........',
    '............KKKKKKKKwKKKKKKKK...........',
    '...................KKK..................',
  ] },
  paw0: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '...............K.........K..............',
    '...............K.........K..............',
    '..............KIK.......KIK.............',
    '..............KIK.......KIK.............',
    '.............KKIKK.KKK.KKIKK............',
    '.............KKIKKKKKKKKKIKK............',
    '............KKIIIKKKKKKKIIIKK...........',
    '............KKKKKKKKKKKKKKKKK...........',
    '............KKKEPEKKKKKEPEKKK...........',
    '........www.KKKEPEKKKKKEPEKKKwww........',
    '...........KKKKEEEKKKKKEEEKKKK..........',
    '.........ww.KKKKKKKKKKKKKKKKKww.........',
    '............KKKKKKKKNKKKKKKKK...........',
    '.............KKKKKKNKNKKKKKK............',
    '..............KKKKKKKKKKKKK.............',
    '...............KKKKKKKKKKK..............',
    '..............KKKKKKKKKKKKK.............',
    '..............KKKKKKKKKKKKK....K........',
    '.........K....KKKKKKKKKKKKK...KKKK......',
    '........KwK...KKKKKKKKKKKKK....KKKK.....',
    '.......KKKKK.KKKKKKKKKKKKKKK.....KKK....',
    '........KKKKKKKKKKKKKKKKKKKKK.....KK....',
    '.........KKKKKKKKKKKKKKKKKKKK.....KK....',
    '...........KKKKKKKKKKKKKKKKKKK...KKK....',
    '...........KKKKKKKKKKKKKKKKKKK.KKKK.....',
    '...........KKKKKKKKKKKKKKKKKKKKKKKK.....',
    '...........KKKKKKKKKwKKKKKKKKKKKK.......',
    '...........KKKKKKKKKwKKKKKKKKKK.........',
    '............KKKKKKKKwKKKKKKKK...........',
    '...................KKK..................',
  ] },
  paw1: { anchorX: 20, rows: [
    '........................................',
    '...............K.........K..............',
    '...............K.........K..............',
    '..............KIK.......KIK.............',
    '..............KIK.......KIK.............',
    '.............KKIKK.KKK.KKIKK............',
    '.............KKIKKKKKKKKKIKK............',
    '............KKIIIKKKKKKKIIIKK...........',
    '............KKKKKKKKKKKKKKKKK...........',
    '............KKKEPEKKKKKEPEKKK...........',
    '........www.KKKEPEKKKKKEPEKKKwww........',
    '...........KKKKEEEKKKKKEEEKKKK..........',
    '.........ww.KKKKKKKKKKKKKKKKKww.........',
    '............KKKKKKKKNKKKKKKKK...........',
    '.............KKKKKKNKNKKKKKK............',
    '..............KKKKKKKKKKKKK.............',
    '...............KKKKKKKKKKK..............',
    '.....K........KKKKKKKKKKKKK.............',
    '....KwK.......KKKKKKKKKKKKK.............',
    '...KKKKK......KKKKKKKKKKKKK....K........',
    '....KKKKKKK...KKKKKKKKKKKKK...KKKK......',
    '.....KKKKKKKK.KKKKKKKKKKKKK....KKKK.....',
    '.......KKKKKKKKKKKKKKKKKKKKK.....KKK....',
    '.........KKKKKKKKKKKKKKKKKKKK.....KK....',
    '...........KKKKKKKKKKKKKKKKKK.....KK....',
    '...........KKKKKKKKKKKKKKKKKKK...KKK....',
    '...........KKKKKKKKKKKKKKKKKKK.KKKK.....',
    '...........KKKKKKKKKKKKKKKKKKKKKKKK.....',
    '...........KKKKKKKKKwKKKKKKKKKKKK.......',
    '...........KKKKKKKKKwKKKKKKKKKK.........',
    '............KKKKKKKKwKKKKKKKK...........',
    '...................KKK..................',
  ] },
  stand0: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '.............................K..........',
    '.............................KI.........',
    '.........KK..............S...KII........',
    '........KKK..............SS.KKKKK.......',
    '........KK...............SSKKKKKK.......',
    '........KK................KKKKKKKK......',
    '.......KKK................KKKKKEEEK...w.',
    '.......KKK...............KKKKKKPPEK..w..',
    '.......KKK...............KKKKKKKKKKN....',
    '.......KKKK..............KKKKKKKKKKK....',
    '........KKK..............KKKKKBBBBKK.w..',
    '........KKKK............KKKKKKBBBB......',
    '........KKKKKKKKKKKKKKKKKKKKKKK.........',
    '.........KKKKKKKKKKKKKKKKKKKK...........',
    '.........KKKKKKKKKKKKKKKKKKK............',
    '..........KKKKKKKKKKKKKKKKKK............',
    '...........KKKKKKKKKKKKKKKKK............',
    '...........KKKKKKKKKKKKKKKKK............',
    '............KKKKKBBBBBKKKKK.............',
    '...........SKKKKK.....BKKK..............',
    '...........SSKKK......SSKKK.............',
    '...........SSKK........SSKK.............',
    '............SKK.......SSKKK.............',
    '............SKKK......SSKK..............',
    '............SSKKK.....SSKKK.............',
    '.............SKKK.....SSKKK.............',
    '........................................',
  ] },
  stand1: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '.............................K..........',
    '.........................S...KI.........',
    '.........KK..............SS..KII........',
    '.........KK..............SSSKKKKK.......',
    '........KK................KKKKKKKK......',
    '........KK................KKKKKKKK......',
    '.......KKK...............KKKKKKEEEK...w.',
    '.......KKK...............KKKKKKPPEK..w..',
    '.......KKK...............KKKKKKKKKKN....',
    '.......KKKK..............KKKKKKBBKKK....',
    '........KKK.............KKKKKKBBBBK..w..',
    '........KKKK..KKK.....KKKKKKKKKBBB......',
    '........KKKKKKKKKKKKKKKKKKKKK...........',
    '.........KKKKKKKKKKKKKKKKKKK............',
    '.........KKKKKKKKKKKKKKKKKKK............',
    '..........KKKKKKKKKKKKKKKKKK............',
    '...........KKKKKKKKKKKKKKKKK............',
    '...........KKKKKKKKKKKKKKKKK............',
    '............KKKKKBBBBBBKKKK.............',
    '...........SKKKK......SSKKK.............',
    '...........SSKK.......SSKKK.............',
    '...........SSKK........SKKK.............',
    '............SKK.......SSKKK.............',
    '............SKKK......SSKK..............',
    '............SSKKK.....SSKKK.............',
    '.............SKKK.....SSKKK.............',
    '........................................',
  ] },
  stand0e: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '.........KK..............S...KKK........',
    '........KKK..............SS.KKKKK.......',
    '........KK...............SSKKKKKK.......',
    '........KK................KKKKKKKK......',
    '.......KKK................KKKKKEEEK...w.',
    '.......KKK...............KKKKKKPPEK..w..',
    '.......KKK...............KKKKKKKKKKN....',
    '.......KKKK..............KKKKKKKKKKK....',
    '........KKK..............KKKKKBBBBKK.w..',
    '........KKKK............KKKKKKBBBB......',
    '........KKKKKKKKKKKKKKKKKKKKKKK.........',
    '.........KKKKKKKKKKKKKKKKKKKK...........',
    '.........KKKKKKKKKKKKKKKKKKK............',
    '..........KKKKKKKKKKKKKKKKKK............',
    '...........KKKKKKKKKKKKKKKKK............',
    '...........KKKKKKKKKKKKKKKKK............',
    '............KKKKKBBBBBKKKKK.............',
    '...........SKKKKK.....BKKK..............',
    '...........SSKKK......SSKKK.............',
    '...........SSKK........SSKK.............',
    '............SKK.......SSKKK.............',
    '............SKKK......SSKK..............',
    '............SSKKK.....SSKKK.............',
    '.............SKKK.....SSKKK.............',
    '........................................',
  ] },
  stand1e: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '.........................S..............',
    '.........KK..............SS..KKK........',
    '.........KK..............SSSKKKKK.......',
    '........KK................KKKKKKKK......',
    '........KK................KKKKKKKK......',
    '.......KKK...............KKKKKKEEEK...w.',
    '.......KKK...............KKKKKKPPEK..w..',
    '.......KKK...............KKKKKKKKKKN....',
    '.......KKKK..............KKKKKKBBKKK....',
    '........KKK.............KKKKKKBBBBK..w..',
    '........KKKK..KKK.....KKKKKKKKKBBB......',
    '........KKKKKKKKKKKKKKKKKKKKK...........',
    '.........KKKKKKKKKKKKKKKKKKK............',
    '.........KKKKKKKKKKKKKKKKKKK............',
    '..........KKKKKKKKKKKKKKKKKK............',
    '...........KKKKKKKKKKKKKKKKK............',
    '...........KKKKKKKKKKKKKKKKK............',
    '............KKKKKBBBBBBKKKK.............',
    '...........SKKKK......SSKKK.............',
    '...........SSKK.......SSKKK.............',
    '...........SSKK........SKKK.............',
    '............SKK.......SSKKK.............',
    '............SKKK......SSKK..............',
    '............SSKKK.....SSKKK.............',
    '.............SKKK.....SSKKK.............',
    '........................................',
  ] },
  stand0a: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '..........................K.....K.......',
    '..........................KI....KI......',
    '.........KK...............KIK...KIK.....',
    '........KKK...............KKKKKKKKKK....',
    '........KK.................KKKKKKK......',
    '........KK................KKKKKKKKK.....',
    '.......KKK................KKEPKPEKK.....',
    '.......KKK..............w.KKEPKPEKK.w...',
    '.......KKK...............wKKKKKKKKKw....',
    '.......KKKK...............KKKKNKKKK.....',
    '........KKK...............KKBBBBBKK.....',
    '........KKKK...............KBBBBBK......',
    '........KKKKKKKKKKKKKKKK....KBBBK.......',
    '.........KKKKKKKKKKKKKKK................',
    '.........KKKKKKKKKKKKKKK................',
    '..........KKKKKKKKKKKKKKKKKK............',
    '...........KKKKKKKKKKKKKKKKK............',
    '...........KKKKKKKKKKKKKKKKK............',
    '............KKKKKBBBBBKKKKK.............',
    '...........SKKKKK.....BKKK..............',
    '...........SSKKK......SSKKK.............',
    '...........SSKK........SSKK.............',
    '............SKK.......SSKKK.............',
    '............SKKK......SSKK..............',
    '............SSKKK.....SSKKK.............',
    '.............SKKK.....SSKKK.............',
    '........................................',
  ] },
  stand1a: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '..........................K.....K.......',
    '..........................KI....KI......',
    '.........KK...............KIK...KIK.....',
    '........KKK...............KKKKKKKKKK....',
    '........KK.................KKKKKKK......',
    '........KK................KKKKKKKKK.....',
    '.......KKK................KKEPKPEKK.....',
    '.......KKK..............w.KKEPKPEKK.w...',
    '.......KKK...............wKKKKKKKKKw....',
    '.......KKKK...............KKKKNKKKK.....',
    '........KKK...............KKBBBBBKK.....',
    '........KKKK..KKK.....KK...KBBBBBK......',
    '........KKKKKKKKKKKKKKKK....KBBBK.......',
    '.........KKKKKKKKKKKKKKK................',
    '.........KKKKKKKKKKKKKKK................',
    '..........KKKKKKKKKKKKKKKKKK............',
    '...........KKKKKKKKKKKKKKKKK............',
    '...........KKKKKKKKKKKKKKKKK............',
    '............KKKKKBBBBBBKKKK.............',
    '...........SKKKK......SSKKK.............',
    '...........SSKK.......SSKKK.............',
    '...........SSKK........SKKK.............',
    '............SKK.......SSKKK.............',
    '............SKKK......SSKK..............',
    '............SSKKK.....SSKKK.............',
    '.............SKKK.....SSKKK.............',
    '........................................',
  ] },
  walk0: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '.............................K..........',
    '........KK...................KI.........',
    '.......KKK...............S...KII........',
    '.......KK................SS.KKKKK.......',
    '.......KK................SSKKKKKK.......',
    '......KKK.................KKKKKKKK......',
    '......KKK.................KKKKKEEEK...w.',
    '......KKK................KKKKKKPPEK..w..',
    '......KKKK...............KKKKKKKKKKN....',
    '.......KKK...............KKKKKKKKKKK....',
    '.......KKKK..............KKKKKBBBBKK.w..',
    '.......KKKKK............KKKKKKBBBB......',
    '........KKKK.KKKKKKKKKKKKKKKKKK.........',
    '........KKKKKKKKKKKKKKKKKKKKK...........',
    '.........KKKKKKKKKKKKKKKKKKK............',
    '..........KKKKKKKKKKKKKKKKKK............',
    '...........KKKKKKKKKKKKKKKKK............',
    '...........KKKKKKKKKKKKKKKKK............',
    '............KKKKKBBBBBKKKKK.............',
    '............KKKKK....SBKKKK.............',
    '...........KKKKK.....SS..KKK............',
    '...........KKKSS....SSS...KK............',
    '...........KK.SSSS.SSS....KKK...........',
    '...........KK..SSS.SSS.....KK...........',
    '...........KKK.............KKK..........',
    '...........KKK.............KKK..........',
    '........................................',
  ] },
  walk1: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '.............................K..........',
    '.........KKK.............S...KI.........',
    '.........KK..............SS..KII........',
    '........KK...............SSSKKKKK.......',
    '.......KKK................KKKKKKKK......',
    '.......KKK................KKKKKKKK......',
    '.......KKK...............KKKKKKEEEK...w.',
    '.......KKK...............KKKKKKPPEK..w..',
    '.......KKK................KKKKKKKKKN....',
    '.......KKKK..............KKKKKKBBBKK....',
    '.......KKKK.............KKKKKKBBBBK..w..',
    '........KKKK..KKKK...KKKKKKKKKKBBB......',
    '........KKKKKKKKKKKKKKKKKKKKK...........',
    '.........KKKKKKKKKKKKKKKKKKK............',
    '.........KKKKKKKKKKKKKKKKKKK............',
    '..........KKKKKKKKKKKKKKKKKK............',
    '...........KKKKKKKKKKKKKKKKK............',
    '...........KKKKKKKKKKKKKKKKK............',
    '...........SKKKKKBBBBBBKKKK.............',
    '...........SKKKK......SSKKK.............',
    '...........SSKK........SSKK.............',
    '...........SSKKK.......SSKK.............',
    '...........SSSKK.......SKKK.............',
    '............SSKKKK.....SKKKK............',
    '............SSSKKK.....SSS..............',
    '............SSS........SSS..............',
    '........................................',
  ] },
  walk2: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '.............................K..........',
    '........KK...................KI.........',
    '........KK...............S...KII........',
    '.......KKK...............SS.KKKKK.......',
    '.......KK................SSKKKKKK.......',
    '.......KKK................KKKKKKKK......',
    '.......KKK................KKKKKEEEK...w.',
    '.......KKK...............KKKKKKPPEK..w..',
    '.......KKK...............KKKKKKKKKKN....',
    '.......KKKK..............KKKKKKKKKKK....',
    '........KKK..............KKKKKBBBBKK.w..',
    '........KKKK............KKKKKKBBBB......',
    '........KKKK.KKKKKKKKKKKKKKKKKK.........',
    '.........KKKKKKKKKKKKKKKKKKKK...........',
    '.........KKKKKKKKKKKKKKKKKKK............',
    '..........KKKKKKKKKKKKKKKKKK............',
    '...........KKKKKKKKKKKKKKKKK............',
    '...........KKKKKKKKKKKKKKKKK............',
    '...........SKKKKKBBBBBKKKKK.............',
    '..........SSKKKKK.....BKKK..............',
    '..........SS.KKK.......KKK..............',
    '..........SS..KK.......KKSS.............',
    '.........SSSS.KKK.....KKKSSS............',
    '..........SS...KKK....KK.SSS............',
    '................KKKK.KKK................',
    '................KKKK.KKK................',
    '........................................',
  ] },
  walk3: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '.............................K..........',
    '.........KKK.............S...KI.........',
    '.........KK..............SS..KII........',
    '........KKK..............SSSKKKKK.......',
    '........KKK...............KKKKKKKK......',
    '........KK................KKKKKKKK......',
    '........KK................KKKKKEEEK...w.',
    '........KKK..............KKKKKKPPEK..w..',
    '........KKK..............KKKKKKKKKKN....',
    '........KKK..............KKKKKKBBKKK....',
    '........KKKK............KKKKKKBBBBK..w..',
    '........KKKK..KKK.....KKKKKKKKKBBB......',
    '.........KKKKKKKKKKKKKKKKKKKK...........',
    '.........KKKKKKKKKKKKKKKKKKK............',
    '.........KKKKKKKKKKKKKKKKKKK............',
    '..........KKKKKKKKKKKKKKKKKK............',
    '...........KKKKKKKKKKKKKKKKK............',
    '...........KKKKKKKKKKKKKKKKK............',
    '............KKKKKBBBBBBKKKK.............',
    '............KKKK......SSKKK.............',
    '...........SKKK.......SS.KK.............',
    '............KKK.......SS.KK.............',
    '.............KKS.....SSS.KK.............',
    '.............KKS.....SSS.KK.............',
    '.............KKK........KKKK............',
    '.............KKKK.......KKKK............',
    '........................................',
  ] },
  run0: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '..............................K.........',
    '..............................KI........',
    '..........................S...KII.......',
    '..........................SS.KKKKK......',
    '.KK.......................SSKKKKKK......',
    '.KKK.......................KKKKKKKK.....',
    '..KK.......................KKKKKEEEK...w',
    '..KKK.....................KKKKKKPPEK..w.',
    '...KKK....................KKKKKKKKKKN...',
    '....KKK...................KKKKKKKKKKK...',
    '....KKKKK................KKKKKKBBBBKK.w.',
    '.....KKKKK..............KKKKKKKBBBB.....',
    '......KKKKKKKKKKKKKKKKKKKKKKKKKK........',
    '.......KKKKKKKKKKKKKKKKKKKKKK...........',
    '........KKKKKKKKKKKKKKKKKKKK............',
    '.........KKKKKKKKKKKKKKKKKKK............',
    '..........KKKKKKKKKKKKKKKKKK............',
    '...........KKKKKKKKKKKKKKKKK............',
    '..........SKKKKKKBBBBBBKKKK.............',
    '..........KKKKKK.......SKKKK............',
    '.........SKKKKK.........SSKKK...........',
    '.........KKK.............SSKK...........',
    '.........KK..............SSSKK..........',
    '........KKKK.............SSSKK..........',
    '.........KKK.................KKK........',
    '........SSSS.................KKK........',
    '........................................',
    '........................................',
  ] },
  run1: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '........................................',
    '..............................K.........',
    '..............................KI........',
    '..........................S...KII.......',
    '..........................SS.KKKKK......',
    '.KK.......................SSKKKKKK......',
    '.KK........................KKKKKKKK.....',
    '..KK.......................KKKKKEEEK...w',
    '..KKK.....................KKKKKKPPEK..w.',
    '...KKK....................KKKKKKKKKKN...',
    '...KKKK...........KK......KKKKKKKKKKK...',
    '....KKKKK.......KKKKKKK..KKKKKKBBBBK..w.',
    '.....KKKKK...KKKKKKKKKKKKKKKKKKBBBB.....',
    '......KKKKKKKKKKKKKKKKKKKKKKKK..........',
    '.......KKKKKKKKKKKKKKKKKKKKKK...........',
    '........KKKKKKKKKKKKKKKKKKKK............',
    '..........KKKKKKKKKKKKKKKKKK............',
    '...........KKKKKKBBBBKKKKKKK............',
    '...........KKKKKK....BKKKKK.............',
    '...........KKKKK......BKKKK.............',
    '............KKKK.......SSKK.............',
    '............SKKK.......SSKKK............',
    '............SKKK.......SS.KK............',
    '.............SKK......SSSSKK............',
    '..............SKK.....SSS.KKK...........',
    '...............KKK........KKK...........',
    '...............SKKK.....................',
    '................KKK.....................',
    '........................................',
    '........................................',
  ] },
  run2: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '..............................K.........',
    '..............................KI........',
    '..K.......................S...KII.......',
    '.KK.......................SS.KKKKK......',
    '..KK......................SSKKKKKKK.....',
    '..KKK......................KKKKKKKK.....',
    '...KK......................KKKKKEEEK...w',
    '...KKK....................KKKKKKPPEK..w.',
    '....KKK...................KKKKKKKKKKN...',
    '....KKKK..................KKKKKKKKKKK...',
    '.....KKKK................KKKKKKBBBBK..w.',
    '......KKKKK...KKK....KKKKKKKKKKBBBB.....',
    '.......KKKKKKKKKKKKKKKKKKKKKKK..........',
    '........KKKKKKKKKKKKKKKKKKKKK...........',
    '.........KKKKKKKKKKKKKKKKKKK............',
    '..........KKKKKKKKKKKKKKKKKK............',
    '...........KKKKKKKKKKKKKKKKK............',
    '...........KKKKKKKBKKKKKKKKK............',
    '...........KKKKKKB.BBBBKKKK.............',
    '............KKKK.....SSKKK..............',
    '............SKKKK...SSSKK...............',
    '.............SSKKK.SSS.KK...............',
    '..............SSKKKSS.KKK...............',
    '...............SSKKKK.KK................',
    '.................SKKKKKK................',
    '....................KKK.................',
    '....................KKK.................',
    '........................................',
  ] },
  run3: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '........................................',
    '..............................K.........',
    '..........................S...KI........',
    '..........................SS..KII.......',
    '.KK.......................SSKKKKKK......',
    '..KK.......................KKKKKKKK.....',
    '..KKK......................KKKKKEEEK....',
    '..KKK.....................KKKKKKPPEK...w',
    '...KKK....................KKKKKKKKKKK.w.',
    '....KKK....................KKKKKKKKKN...',
    '....KKKKK........KKKKK...KKKKKKBBBBKK...',
    '.....KKKKK....KKKKKKKKKKKKKKKKKBBBB...w.',
    '......KKKKKKKKKKKKKKKKKKKKKKKKKKKB......',
    '.......KKKKKKKKKKKKKKKKKKKKKK...........',
    '........KKKKKKKKKKKKKKKKKKKK............',
    '..........KKKKKKKKKKKKKKKKKK............',
    '...........KKKKKKKBBKKKKKKKK............',
    '...........KKKKKKB..BBKKKKKK............',
    '..........SKKKKK......BKKKK.............',
    '..........SSKKKK......SSKK..............',
    '.........SSKKKK.......SSKK..............',
    '.........SSKKK.......SSSKK..............',
    '.........SS.KK.......SS.KK..............',
    '.........SS.KK.......SSKK...............',
    '.........SSSKKK.....SSKKKK..............',
    '.........SSSKKK....SSSSKK...............',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
  ] },
  stretch0: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '.............................K..........',
    '.............................KI.........',
    '........K................S...KII........',
    '.......KK................SS.KKKKK.......',
    '.......KK................SSKKKKKK.......',
    '......KKK.................KKKKKKKK......',
    '......KK..................KKKKKEEEK...w.',
    '......KK.................KKKKKKPPEK..w..',
    '......KKK................KKKKKKKKKKN....',
    '......KKK................KKKKKKKKKKK....',
    '......KKK................KKKKKBBBBKK.w..',
    '......KKKK..............KKKKKKBBBB......',
    '......KKKKK..KKKKKK.KKKKKKKKKKK.........',
    '.......KKKK.KKKKKKKKKKKKKKKKK...........',
    '.......KKKKKKKKKKKKKKKKKKKKK............',
    '........KKKKKKKKKKKKKKKKKKKK............',
    '.........KKKKKKKKKKKKKKKKKKK............',
    '...........KKKKKKKKKKKKKKKKK............',
    '............KKKKKKKBKKKKKKKK............',
    '...........SKKKKKBB.BBBKKKK.............',
    '...........SKKKK......SSKKK.............',
    '...........SSKK........SKKK.............',
    '...........SSKK.......SSKKK.............',
    '............SKKK......SSKK..............',
    '............SSKKK.....SSKKK.............',
    '.............SKKK.....SSKKK.............',
    '........................................',
  ] },
  stretch1: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '......KK................................',
    '......KK................................',
    '.....KKK................................',
    '.....KKK................................',
    '.....KKK................................',
    '.....KKK................................',
    '.....KKK................................',
    '.....KKK......................K.........',
    '.....KKKK.....................KI........',
    '......KKK.................S...KII.......',
    '......KKKK...KK...........SS.KKKKK......',
    '......KKKKKKKKKK..........SSKKKKKK......',
    '.......KKKKKKKKKKK.........KKKKKKKK.....',
    '........KKKKKKKKKKK.......KKKKKKKKK.....',
    '.........KKKKKKKKKKKK.....KKKKKwwwKK...w',
    '..........KKKKKKKKKKKKKKKKKKKKKKKKKK..w.',
    '..........KKKKKKKKKKKKKKKKKKKKKKKKKKN...',
    '.........SSKKKKKKKKKKKKKKKKKKKKBBBBKK...',
    '.........SKKKKKKKKKKKKKKKKKKKKKBBBBK..w.',
    '........SSKKKKK.KKKKKKKKKKKKKKKK........',
    '.......SSKKK.....BBBKKKKKKKKK...........',
    '........SKKK........BBBKKKKKK...........',
    '........SSKK...........KKKKKK...........',
    '........SSKK.............SSKKK..........',
    '........SSKKK.............SSKKKK........',
    '........SSKKK..............SSKKK........',
    '........................................',
  ] },
  stretch2: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '.......KK...............................',
    '......KKK...............................',
    '......KK................................',
    '......KK................................',
    '......KK................................',
    '......KK................................',
    '......KK................................',
    '......KKK...............................',
    '......KKK...............................',
    '......KKKK..............................',
    '......KKKKK.............................',
    '.......KKKKKKKKK..............K.........',
    '.......KKKKKKKKKK.........S...KI........',
    '........KKKKKKKKKK........SS..KII.......',
    '.........KKKKKKKKKK.......SSKKKKKK......',
    '..........KKKKKKKKKK.......KKKKKKKK.....',
    '...........KKKKKKKKKK......KKKKKKKKK....',
    '..........SKKKKKKKKKKKKKKKKKKKKKwwwK...w',
    '.........SSKKKKKKKKKKKKKKKKKKKKKKKKK..w.',
    '.........SKKKKKKKKKKKKKKKKKKKKKKKKKKN...',
    '........SSKKK...KKKKKKKKKKKKKKKBBBBKK...',
    '.......SSKKK.....BKKKKKKKKKKKKKBBBBK..w.',
    '........SSKK......BBKKKKKKKKKKKKKB......',
    '........SSKK........BBBBKKKKK...........',
    '........SSKK............KKKKKKK.........',
    '.........SSKKK............SSKKKKKK......',
    '.........SKKKK..............SSKKKK......',
    '........................................',
  ] },
  startle0: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '.........K..............................',
    '........KK..............................',
    '........KK....................K.........',
    '........KK.................S..KI........',
    '.......KKK.................SS.KII.......',
    '.......KKK.................SKKKKKK......',
    '.......KKK.................KKKKKKKK.....',
    '.......KKK.................KKKKKKKKK....',
    '.......KKKK...............KKKKKKEEEK...w',
    '.......KKKK...............KKKKKKPPEKK.w.',
    '.......KKKK...............KKKKKKKKKKN...',
    '.......KKKK.......KKKK....KKKKKKBBBKK...',
    '.......KKKKK....KKKKKKKK.KKKKKKBBBBBK.w.',
    '.......KKKKK..KKKKKKKKKKKKKKKKKKBBB.....',
    '.......KKKKKKKKKKKKKKKKKKKKKKKKK........',
    '.......KKKKKKKKKKKKKKKKKKKKKK...........',
    '.......KKKKKKKKKKKKKKKKKKKKK............',
    '........KKKKKKKKKKKKKKKKKKKK............',
    '........KKKKKKKKKKBBKKKKKKKK............',
    '...........KKKKKKB..BKKKKKKK............',
    '............KKKKK....BBKKKK.............',
    '...........SKKKK......SKKKK.............',
    '...........SKKKK.......SSKK.............',
    '...........SKKK........SSKK.............',
    '...........SKK.........SSKK.............',
    '...........SKK.........SSKK.............',
    '...........SKKK........SSKK.............',
    '...........SSKKK.......SSKKK............',
    '............KKKK.......SSKKK............',
    '........................................',
  ] },
  pounce0: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '..............................K.........',
    '.K........................S...KI........',
    '.KK.......................SS..KII.......',
    '.KKK......................SSKKKKKK......',
    '..KKK......................KKKKKKK......',
    '..KKKK.......KK...........KKKKKKKKK.....',
    '...KKKKKKKKKKKKKKKK......KKKKKKEEEK....w',
    '....KKKKKKKKKKKKKKKKKKKKKKKKKKKPPEKK..w.',
    '.....KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKN...',
    '.......KKKKKKKKKKKKKKKKKKKKKKKKKBBKKK...',
    '..........KKKKKKKKKKKKKKKKKKKKKBBBBK..w.',
    '..........KKKKKKKKKKKKKKKKKKKKKBBB......',
    '.........SKKKKKKKKKKKKKKKKKKK...........',
    '........SSKKKKK..BBBBBBKKKKK............',
    '........SKKKKK..........SKKKK...........',
    '........SSKKK............SKKK...........',
    '.........SSKKK..........SSKKK...........',
    '.........SSKKK..........SKKKK...........',
    '........................................',
  ] },
  pounce1: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '................................K.......',
    '................................KI......',
    '............................S...KII.....',
    '............................SS.KKKKK....',
    '.K..........................SSKKKKKK....',
    '.KK..........................KKKKKKKK...',
    '.KKK.........................KKKKKEEEK..',
    '..KK........................KKKKKKPPEK..',
    '..KKK.......................KKKKKKKKKKN.',
    '...KKK..............KKKKKKKKKKKKKKKKKKK.',
    '...KKKK..........KKKKKKKKKKKKKKKKBBBBKK.',
    '....KKKKK......KKKKKKKKKKKKKKKKKKBBBB...',
    '.....KKKKK..KKKKKKKKKKKKKKKKKKKKKKK.....',
    '......KKKKKKKKKKKKKKKKKKKKKKKKKKKKK.....',
    '.......KKKKKKKKKKKKKKKKKKKKKKKKKSS......',
    '........KKKKKKKKKKKKKBBBBBKKKKK.........',
    '.........KKKKKKKKKKBB......KK...........',
    '...........KKKKKKKB.....................',
    '.........SKKKKKKK.......................',
    '........SKKKKKKK........................',
    '.......SKKK.KKKK........................',
    '.......SKKK.............................',
    '......SSSS..............................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
  ] },
  pounce2: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '.KK.....................................',
    '.KK...........................K.........',
    '..KK......................S...KI........',
    '..KKK.....................SS..KII.......',
    '..KKKK....................SSKKKKKK......',
    '...KKKK....................KKKKKKKK.....',
    '....KKKK.....KK............KKKKKEEEK....',
    '.....KKKKKKKKKKKKKKKKKKKKKKKKKKKPPEK...w',
    '.....KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK.w.',
    '.......KKKKKKKKKKKKKKKKKKKKKKKKKKKKKN...',
    '........KKKKKKKKKKKKKKKKKKKKKKKBBBBKK...',
    '..........KKKKKKKKKKKKKKKKKKKKKBBBB...w.',
    '..........KKKKKKKKKKKKKKKKKKKKKKKB......',
    '.........SSKKKKKKBBBBKKKKKKKKK..........',
    '........SSKKKKK......BBBKKKKK...........',
    '........SKKKKK..........SKKKK...........',
    '........SSKK.............SSKK...........',
    '........SSKK..............SKKK..........',
    '.........SSKKK............SSKKK.........',
    '.........SKKKK............SSKKK.........',
    '........................................',
  ] },
  jump0: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '..............................K.........',
    '..............................KI........',
    '.KK.......................S...KII.......',
    '.KKK......................SS.KKKKK......',
    '..KKK.....................SSKKKKKK......',
    '..KKKK.....................KKKKKKKK.....',
    '...KKKKK....KKKKK.........KKKKKEEEK....w',
    '....KKKKKKKKKKKKKKKKKKKKKKKKKKKPPEKK..w.',
    '.....KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKN...',
    '......KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK...',
    '........KKKKKKKKKKKKKKKKKKKKKKKBBBBK..w.',
    '..........KKKKKKKKKKKKKKKKKKKKKBBBB.....',
    '..........SKKKKKKKKKKKKKKKKKKKKK........',
    '........SSKKKKKKKBBBBBBKKKKKK...........',
    '........SKKKKKK........BKKKKK...........',
    '........SSKKK............SKKK...........',
    '.........SSKKKK.........SKKK............',
    '..........SKKKK........SSKKKK...........',
    '........................................',
  ] },
  jump1: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '.........K..............................',
    '........KK....................K.........',
    '........KK....................KI........',
    '.......KKK................S...KII.......',
    '.......KK.................SS.KKKKK......',
    '......KKK.................SSKKKKKK......',
    '......KKK..................KKKKKKKK.....',
    '......KKK.................KKKKKEEEK....w',
    '......KKKK................KKKKKPPEKK..w.',
    '......KKKK.........KKKKKKKKKKKKKKKKKN...',
    '......KKKKK...KKKKKKKKKKKKKKKKKKKKKKK...',
    '.......KKKK.KKKKKKKKKKKKKKKKKKKBBBBK..w.',
    '.......KKKKKKKKKKKKKKKKKKKKKKKKBBBB.....',
    '........KKKKKKKKKKKKKKKKKKKKKKKK........',
    '........KKKKKKKKKKKKKKKKKKKKKK..........',
    '.........KKKKKKKKKKKBKKKKKKKK...........',
    '..........KKKKKKKBBB.BBBKKKK............',
    '.........SSKKKKKK.......SSKKK...........',
    '........SSKKKKKK.........SSKK...........',
    '.......SSKKKKKK..........SSKKK..........',
    '........SSKK.............SKKKK..........',
    '........SSKKK............SSS............',
    '........SSKK............................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
  ] },
  jump2: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........K...............................',
    '.......KKK..............................',
    '.......KK...............................',
    '......KKK.....................K.........',
    '......KKK.................S...KI........',
    '......KKK.................SS..KII.......',
    '......KKK.................SSKKKKKK......',
    '......KKK..................KKKKKKKK.....',
    '......KKK.................KKKKKEEEK.....',
    '......KKKK................KKKKKPPEKK...w',
    '......KKKKK.KKKKKKKKKKKKKKKKKKKKKKKK..w.',
    '.......KKKKKKKKKKKKKKKKKKKKKKKKKKKKKN...',
    '.......KKKKKKKKKKKKKKKKKKKKKKKKBBBBKK...',
    '........KKKKKKKKKKKKKKKKKKKKKKKBBBB...w.',
    '.........KKKKKKKKKKKKKKKKKKKKKKKK.......',
    '..........KKKKKKKKKKKKKKKKKKKK..........',
    '..........KKKKKKKBBBBKKKKKKKK...........',
    '.........SSKKKKK.....BBBKKKKK...........',
    '.........SKKKKK.........SKKK............',
    '........SSKKKK..........SSKKK...........',
    '........SSKK.............SKKK...........',
    '.........SKKK...........SSKK............',
    '.........SSKKK..........SSKKK...........',
    '.........SSKKK..........SSKKK...........',
    '........................................',
  ] },
  sleep0: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '...............KKKKKKK..................',
    '..............KKKKKKKKKK................',
    '.............KKKKKKKKKKK................',
    '............KKKKKKKKKKKKK...............',
    '............KKKKKKKKKKKKK...............',
    '............KKKKKKKKKKKKIKKK............',
    '.............KKKKKKKKKwKKKKKK...........',
    '.............KKKKKKKKKwKKKKKKK..........',
    '............KKKKBBBBBKwKKKwwwKK.w.......',
    '............KBBBBBBBBBwKKKKKKKN.........',
    '............KBBBBBBBBBwKKKKKKKK.w.......',
    '.............KKBBBBBBBKBBBBBBK..........',
    '...............KKKKKKKKBBBBBB...........',
    '...................KKKKK................',
    '........................................',
  ] },
  sleep1: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '................KKKKKK..................',
    '..............KKKKKKKKK.................',
    '.............KKKKKKKKKKK................',
    '............KKKKKKKKKKKKK...............',
    '............KKKKKKKKKKKKK...............',
    '............KKKKKKKKKKKKK...............',
    '............KKKKKKKKKKKKIKKKK...........',
    '............KKKKKKKKKKwKKKKKKK..........',
    '............KKKKKKKKKKwKKKwwwK..........',
    '............KKKBBBBBBBwKKKKKKKK.w.......',
    '............KBBBBBBBBBwKKKKKKKN.........',
    '............KBBBBBBBBBwBBBBBKKK.w.......',
    '..............KKBBBBBKBBBBBBB...........',
    '................KKKKKKKKBBBB............',
    '........................................',
    '........................................',
  ] },
  roll0: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '......................B.................',
    '.....................KKK................',
    '.....................KK.................',
    '.....................KK.................',
    '............SS..B...KKK.................',
    '...........SSS.KK...KKK.................',
    '...........SSS.KK...KKK.SSS.............',
    '...........SS.KKK...KKK.SSS.............',
    '..........SSS.KKK..KKKK.SS..............',
    '..........SSS.KKK..KKKKSSS.KK...........',
    '..K......SSSSKKKK..KKKKSSKKKKKK..w......',
    '..KK.....SSS.KKKKKBKKKSSKKKKKKKN........',
    '..KKK....SSS.KKKBBBKKKBBKKKKEEKK.w......',
    '...KKKK..SSSKKKKBBBKKKBBKKKKPPKK........',
    '....KKKKKKKKKBBBBBBBBBBBKKKKKKKK........',
    '.....KKKKKKKKKBBBBBBBBBBKKKKKKK.........',
    '......KKKKKKKKKKKKKKKKKKKKKIKK..........',
    '........KKKK.KKKKKKKKKKKKKKK............',
    '..............KKKKKKKKKKK.K.............',
    '........................................',
    '........................................',
  ] },
  roll1: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '.....................KB.................',
    '...............KB....KKK................',
    '...............KKK...KK.SSS.............',
    '............S..KK...KKK.SSS.............',
    '............SSKKK...KKK.SSS.............',
    '...........SSSKKK...KKKSSS..............',
    '...........SSSKKK...KKKSSS..............',
    '..........SSSKKKK..KKKKSSS..............',
    '..K.......SSSKKKK..KKKKSSSKKK...........',
    '..KK.....SSSSKKKKKBKKKSSSKKKKKK..w......',
    '..KKK....SSS.KKKBBBKKKBBKKKKKKKN........',
    '..KKKK...SSSKKKKBBBKKKBBKKKKEEKK.w......',
    '...KKKKKKKKKKBBBBBBBBBBBKKKKPPKK........',
    '....KKKKKKKKKKBBBBBBBBBBKKKKKKKK........',
    '.....KKKKKKKKKKKKKKKKKKKKKKKKKK.........',
    '.......KKKKK.KKKKKKKKKKKKKKIKK..........',
    '..............KKKKKKKKKKK.KK............',
    '..........................K.............',
    '........................................',
  ] },
  roll2: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '...............KB........S..............',
    '...............KK....KB.SSS.............',
    '...............KK....KKKSSS.............',
    '..............KKK....KK.SS..............',
    '..............KKK...KKKSSS..............',
    '............SSKKK...KKKSSS..............',
    '...........SSSKKK...KKKSSS..............',
    '...........SSKKKK..KKKKSSS..............',
    '..K.......SSSKKKK..KKKKSS...............',
    '..KK.....SSSSKKKKKBKKKSSS.KKKK..........',
    '..KK.....SSS.KKKBBBKKKBBKKKKKKKK.w......',
    '..KKK....SSSKKKKBBBKKKBBKKKKKKKN........',
    '...KKK...KKKKBBBBBBBBBBBKKKKEEKK.w......',
    '...KKKKKKKKKKKBBBBBBBBBBKKKKPPKK........',
    '....KKKKKKKKKKKKKKKKKKKKKKKKKKKK........',
    '.....KKKKKKK.KKKKKKKKKKKKKKKKKK.........',
    '..............KKKKKKKKKKK.KIKK..........',
    '..........................KK............',
    '..........................K.............',
    '........................................',
  ] },
  roll3: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '.....................KB.................',
    '...............KB....KKK................',
    '...............KKK...KK.SSS.............',
    '............S..KK...KKK.SSS.............',
    '............SSKKK...KKK.SSS.............',
    '...........SSSKKK...KKKSSS..............',
    '...........SSSKKK...KKKSSS..............',
    '..........SSSKKKK..KKKKSSS..............',
    '..K.......SSSKKKK..KKKKSSSKKK...........',
    '..KK.....SSSSKKKKKBKKKSSSKKKKKK..w......',
    '..KKK....SSS.KKKBBBKKKBBKKKKKKKN........',
    '..KKKK...SSSKKKKBBBKKKBBKKKKEEKK.w......',
    '...KKKKKKKKKKBBBBBBBBBBBKKKKPPKK........',
    '....KKKKKKKKKKBBBBBBBBBBKKKKKKKK........',
    '.....KKKKKKKKKKKKKKKKKKKKKKKKKK.........',
    '.......KKKKK.KKKKKKKKKKKKKKIKK..........',
    '..............KKKKKKKKKKK.KK............',
    '..........................K.............',
    '........................................',
  ] },
  scruff0: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '........................................',
    '................K.....K.................',
    '................KKI...KI................',
    '................KIK...KIK...............',
    '................KKKKKKKKKK..............',
    '.................KKKKKKK................',
    '................KKKKKKKKK...............',
    '................KKwwKwwKK...............',
    '..............w.KKKKKKKKK.w.............',
    '...............wKKKKNKKKKw..............',
    '................KKKKBKKKK...............',
    '.................KBBBBBK................',
    '.................KKBBBKK................',
    '................KKKKKKK.................',
    '................KKKKKKK.................',
    '...............KKKKKKKKK................',
    '...............KKKKKKKKK................',
    '...............KKKKKKKKK................',
    '...............KKKBBBKKK................',
    '...............KKBKKKKKK................',
    '................BKKKKKB.................',
    '................BKKKKKB.................',
    '................KKKKKKK.................',
    '...............SSKKKKKS.................',
    '...............SSKKKKKS.................',
    '...............SKKKKKS..................',
    '...............SKKKKKK..................',
    '...............SKKKKKKK.................',
    '................KK.KKKK.................',
    '........................................',
  ] },
  scruff1: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '........................................',
    '................K.....K.................',
    '................KKI...KI................',
    '................KIK...KIK...............',
    '................KKKKKKKKKK..............',
    '.................KKKKKKK................',
    '................KKKKKKKKK...............',
    '................KKwwKwwKK...............',
    '..............w.KKKKKKKKK.w.............',
    '...............wKKKKNKKKKw..............',
    '................KKKKBKKKK...............',
    '.................KBBBBBK................',
    '.................KKBBBKK................',
    '..................KKKKKKK...............',
    '..................KKKKKKK...............',
    '.................KKKKKKKKK..............',
    '.................KKKKKKKKK..............',
    '.................KKKKKKKKK..............',
    '................KKKKBBBKKK..............',
    '...............KKKKBKKKKKK..............',
    '.............KKKKKBKKKKKB...............',
    '.............KKKKKBKKKKKB...............',
    '............KKKK..KKKKKKK...............',
    '...........KKKK...SKKKKKSS..............',
    '...........KKK....SSKKKKKS..............',
    '...........KKK.....SKKKKKS..............',
    '...........KKK.....SKKKKKS..............',
    '............KK.....SKK.KKS..............',
    '............KK......KKKKK...............',
    '........................................',
  ] },
};

/* ------------------------------------------------------------------ */
/* Pose → frame sequences                                              */
/* ------------------------------------------------------------------ */

/**
 * `e` suffixes are ear-flick variants: same pose, one ear folded back. Swapping
 * to them for ~150ms is what an ear twitch is, and because it's a whole frame
 * rather than an overlay it can never land half a pixel off.
 *
 * `a` is the attentive head — turned out of profile to face you. It exists ONLY
 * for standing. A walking cat always uses the profile head, because a cat that
 * strolls left while staring at the camera reads as a broken neck, not as
 * friendliness.
 */
export const POSE_FRAMES: Record<string, string[]> = {
  sit: ['sit0', 'sit1'],
  sitEar: ['sit0e', 'sit1e'],
  groom: ['groom0', 'groom1'],
  stand: ['stand0', 'stand1'],
  standEar: ['stand0e', 'stand1e'],
  standAttentive: ['stand0a', 'stand1a'],
  walk: ['walk0', 'walk1', 'walk2', 'walk3'],
  run: ['run0', 'run1', 'run2', 'run3'],
  roll: ['roll0', 'roll1', 'roll2', 'roll3'],
  pounce: ['pounce0', 'pounce1', 'pounce2'],
  paw: ['paw0', 'paw1'],
  sleep: ['sleep0', 'sleep1'],
  stretch: ['stretch0', 'stretch1', 'stretch2'],
  celebrate: ['jump0', 'jump1', 'jump2'],
  scruff: ['scruff0', 'scruff1'],
  startle: ['startle0'],
};

/* ------------------------------------------------------------------ */
/* Compiler — chars to a tinted, outlined, 1px-per-pixel canvas         */
/* ------------------------------------------------------------------ */

export interface Rect { x: number; y: number; w: number; h: number }

export interface CompiledFrame {
  /** ART_W x ART_H canvas, one canvas pixel per art pixel. Pupils excluded. */
  img: HTMLCanvasElement;
  /** art-x of the feet, so a tail sticking out one side doesn't shift the cat */
  anchorX: number;
  /** one per eye, in draw order; pupils are painted at runtime so they can track */
  pupils: Rect[];
  /** eye-white bounding boxes, used to close the lids for a blink */
  eyes: Rect[];
}

const SILHOUETTE = new Set(['K', 'S', 'B', 'E', 'P', 'N', 'I']);

const CHAR_COLOR: Record<string, keyof CoatPalette> = {
  K: 'body', S: 'shade', B: 'belly', E: 'eye', P: 'eye', N: 'nose', I: 'earInner', w: 'detail',
};

/** 8-connected clusters of eye pixels, so left and right eyes stay independent */
function eyeClusters(rows: string[]): { cells: [number, number][] }[] {
  const seen = new Set<string>();
  const out: { cells: [number, number][] }[] = [];
  for (let y = 0; y < ART_H; y++) {
    for (let x = 0; x < ART_W; x++) {
      const ch = rows[y][x];
      if (ch !== 'E' && ch !== 'P') continue;
      const key = `${x},${y}`;
      if (seen.has(key)) continue;
      const cells: [number, number][] = [];
      const stack: [number, number][] = [[x, y]];
      seen.add(key);
      while (stack.length) {
        const [cx, cy] = stack.pop()!;
        cells.push([cx, cy]);
        for (let dy = -1; dy <= 1; dy++) {
          for (let dx = -1; dx <= 1; dx++) {
            const nx = cx + dx, ny = cy + dy;
            if (nx < 0 || nx >= ART_W || ny < 0 || ny >= ART_H) continue;
            const nch = rows[ny][nx];
            if (nch !== 'E' && nch !== 'P') continue;
            const nkey = `${nx},${ny}`;
            if (seen.has(nkey)) continue;
            seen.add(nkey);
            stack.push([nx, ny]);
          }
        }
      }
      out.push({ cells });
    }
  }
  return out;
}

function bbox(cells: [number, number][]): Rect {
  let x0 = Infinity, y0 = Infinity, x1 = -Infinity, y1 = -Infinity;
  for (const [x, y] of cells) {
    if (x < x0) x0 = x; if (x > x1) x1 = x;
    if (y < y0) y0 = y; if (y > y1) y1 = y;
  }
  return { x: x0, y: y0, w: x1 - x0 + 1, h: y1 - y0 + 1 };
}

function compileFrame(art: { anchorX: number; rows: string[] }, pal: CoatPalette): CompiledFrame {
  const cv = document.createElement('canvas');
  cv.width = ART_W;
  cv.height = ART_H;
  const ctx = cv.getContext('2d')!;
  const rows = art.rows;

  // 1. outline first — every transparent pixel touching the silhouette
  ctx.fillStyle = pal.outline;
  for (let y = 0; y < ART_H; y++) {
    for (let x = 0; x < ART_W; x++) {
      if (rows[y][x] !== '.') continue;
      let touching = false;
      for (let dy = -1; dy <= 1 && !touching; dy++) {
        for (let dx = -1; dx <= 1; dx++) {
          const nx = x + dx, ny = y + dy;
          if (nx < 0 || nx >= ART_W || ny < 0 || ny >= ART_H) continue;
          if (SILHOUETTE.has(rows[ny][nx])) { touching = true; break; }
        }
      }
      if (touching) ctx.fillRect(x, y, 1, 1);
    }
  }

  // 2. the cat itself. Pupils are laid down as eye-white; the renderer paints
  //    the real pupil on top wherever the cat happens to be looking.
  for (let y = 0; y < ART_H; y++) {
    for (let x = 0; x < ART_W; x++) {
      const ch = rows[y][x];
      if (ch === '.') continue;
      const key = CHAR_COLOR[ch];
      if (!key) continue;
      ctx.fillStyle = pal[key];
      ctx.fillRect(x, y, 1, 1);
    }
  }

  const clusters = eyeClusters(rows);
  const eyes: Rect[] = [];
  const pupils: Rect[] = [];
  for (const c of clusters) {
    eyes.push(bbox(c.cells));
    const pupilCells = c.cells.filter(([x, y]) => rows[y][x] === 'P');
    if (pupilCells.length) pupils.push(bbox(pupilCells));
  }

  return { img: cv, anchorX: art.anchorX, pupils, eyes };
}

export type Sheet = Record<string, CompiledFrame>;

const sheetCache = new Map<number, Sheet>();

/** Compiled frames for a coat. Baked once, then reused for the session. */
export function getSheet(coatIndex: number): Sheet | null {
  if (typeof document === 'undefined') return null; // SSR — no canvas to bake into
  const i = ((coatIndex % COATS.length) + COATS.length) % COATS.length;
  const cached = sheetCache.get(i);
  if (cached) return cached;
  const pal = COATS[i];
  const sheet: Sheet = {};
  for (const [name, art] of Object.entries(FRAME_ART)) sheet[name] = compileFrame(art, pal);
  sheetCache.set(i, sheet);
  return sheet;
}
