/**
 * The Canvas Resident's sprite sheet.
 *
 * Every pose is hand-authored pixel art on a fixed 40x32 grid, stored as one
 * character per pixel. Nothing here is computed from the simulation — which is
 * the whole point. The previous cat drew itself from raw fillRect calls at
 * fractional coordinates, so legs changed height mid-stride and the silhouette
 * tore apart at certain zooms. Baked frames can't stretch, can't tear, and a
 * walk cycle either reads as a cat or it doesn't while you're still drawing it.
 *
 * Character legend:
 *   .  transparent      K  body            S  shade (far limbs, depth)
 *   B  belly            E  eye white       P  pupil (drawn at runtime, so the
 *   N  nose             I  inner ear          cat can look at your cursor)
 *   w  light detail — whiskers, closed-eye lines, the seam between two
 *      overlapping forms. Deliberately NOT part of the silhouette, so it
 *      never grows an outline of its own.
 *
 * The outline is never authored. It's dilated from the silhouette at compile
 * time, which means it is always sealed and always exactly one pixel — the
 * single detail that separates "desktop companion" from "blob with ears".
 */

export interface CoatPalette {
  name: string;
  body: string;
  shade: string;
  belly: string;
  outline: string;
  eye: string;
  pupil: string;
  nose: string;
  earInner: string;
  detail: string;
}

/** Midnight is index 0 and heavily favoured — it's the cat this was drawn for. */
export const COATS: CoatPalette[] = [
  { name: 'midnight', body: '#17171C', shade: '#26262F', belly: '#26262F', outline: '#F5F2EA', eye: '#FFFFFF', pupil: '#17171C', nose: '#E4949B', earInner: '#6B3F4A', detail: '#F5F2EA' },
  { name: 'charcoal', body: '#3A3A44', shade: '#4C4C58', belly: '#5A5A66', outline: '#F5F2EA', eye: '#FFE9A8', pupil: '#1A1A20', nose: '#D98A90', earInner: '#7A4F58', detail: '#F5F2EA' },
  { name: 'ginger',   body: '#CF7C34', shade: '#E2934A', belly: '#F6DDB8', outline: '#FFF6E8', eye: '#FFFFFF', pupil: '#2A1C10', nose: '#C9635E', earInner: '#B5675E', detail: '#FFF6E8' },
  { name: 'ash',      body: '#7C7C88', shade: '#93939E', belly: '#C9C9D2', outline: '#F7F5F0', eye: '#FFFFFF', pupil: '#22222A', nose: '#B07E84', earInner: '#9E7078', detail: '#F7F5F0' },
  // a pale cat needs a dark outline or it dissolves into a light canvas
  { name: 'cream',    body: '#E7D3B3', shade: '#F3E6CE', belly: '#FBF3E4', outline: '#5B4632', eye: '#FFFFFF', pupil: '#3A2E22', nose: '#D9918A', earInner: '#DCA79E', detail: '#5B4632' },
];

export const ART_W = 40;
export const ART_H = 32;
export const ART_GROUND = 30;

export const FRAME_ART: Record<string, { anchorX: number; rows: string[] }> = {
  sit0: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '...............K.........K..............',
    '...............K.........K..............',
    '..............KIK.......KIK.............',
    '..............KIK.......KIK.............',
    '.............KKIKK.KKK.KKIKK............',
    '.............KKIKKKKKKKKKIKK............',
    '............KKIIIKKKKKKKIIIKK...........',
    '............KKKKKKKKKKKKKKKKK...........',
    '............KKKEPEKKKKKEPEKKK...........',
    '........www.KKKEPEKKKKKEPEKKKwww........',
    '...........KKKKEEEKKKKKEEEKKKK..........',
    '.........ww.KKKKKKKKKKKKKKKKKww.........',
    '............KKKKKKKKNKKKKKKKK...........',
    '.............KKKKKKwKwKKKKKK............',
    '..............KKKKKKKKKKKKK.............',
    '...............KKKKKKKKKKK..............',
    '..............KKKKKKKKKKKKK.............',
    '..............KKKKKKKKKKKKK....K........',
    '..............KKKKKKKKKKKKK...KKKK......',
    '..............KKKKKKKKKKKKK....KKKK.....',
    '.............KKKKKKKKKKKKKKK.....KKK....',
    '............KKKKKKKKKKKKKKKKK.....KK....',
    '............KKKKKKKKKKKKKKKKK.....KK....',
    '...........KKKKKKKKKKKKKKKKKKK...KKK....',
    '...........KKKKKKKKKKKKKKKKKKK.KKKK.....',
    '...........KKKKKKKKKKKKKKKKKKKKKKKK.....',
    '...........KKKKKKKKKwKKKKKKKKKKKK.......',
    '...........KKKKKKKKKwKKKKKKKKKK.........',
    '............KKKKKKKKwKKKKKKKK...........',
    '...................KKK..................',
  ] },
  sit1: { anchorX: 20, rows: [
    '........................................',
    '...............K.........K..............',
    '...............K.........K..............',
    '..............KIK.......KIK.............',
    '..............KIK.......KIK.............',
    '.............KKIKK.KKK.KKIKK............',
    '.............KKIKKKKKKKKKIKK............',
    '............KKIIIKKKKKKKIIIKK...........',
    '............KKKKKKKKKKKKKKKKK...........',
    '............KKKEPEKKKKKEPEKKK...........',
    '........www.KKKEPEKKKKKEPEKKKwww........',
    '...........KKKKEEEKKKKKEEEKKKK..........',
    '.........ww.KKKKKKKKKKKKKKKKKww.........',
    '............KKKKKKKKNKKKKKKKK...........',
    '.............KKKKKKwKwKKKKKK............',
    '..............KKKKKKKKKKKKK.............',
    '...............KKKKKKKKKKK..............',
    '..............KKKKKKKKKKKKK.............',
    '..............KKKKKKKKKKKKK.............',
    '..............KKKKKKKKKKKKK....K........',
    '..............KKKKKKKKKKKKK...KKKK......',
    '..............KKKKKKKKKKKKK....KKKK.....',
    '.............KKKKKKKKKKKKKKK.....KKK....',
    '............KKKKKKKKKKKKKKKKK.....KK....',
    '............KKKKKKKKKKKKKKKKK.....KK....',
    '...........KKKKKKKKKKKKKKKKKKK...KKK....',
    '...........KKKKKKKKKKKKKKKKKKK.KKKK.....',
    '...........KKKKKKKKKKKKKKKKKKKKKKKK.....',
    '...........KKKKKKKKKwKKKKKKKKKKKK.......',
    '...........KKKKKKKKKwKKKKKKKKKK.........',
    '............KKKKKKKKwKKKKKKKK...........',
    '...................KKK..................',
  ] },
  sit0e: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '...............K........................',
    '...............K........................',
    '..............KIK.......................',
    '..............KIK.......................',
    '.............KKIKK.KKK..................',
    '.............KKIKKKKKKKKKKKKK...........',
    '............KKIIIKKKKKKKKKKKK...........',
    '............KKKKKKKKKKKKKKKK............',
    '............KKKEPEKKKKKEPEKKK...........',
    '........www.KKKEPEKKKKKEPEKKKwww........',
    '...........KKKKEEEKKKKKEEEKKKK..........',
    '.........ww.KKKKKKKKKKKKKKKKKww.........',
    '............KKKKKKKKNKKKKKKKK...........',
    '.............KKKKKKwKwKKKKKK............',
    '..............KKKKKKKKKKKKK.............',
    '...............KKKKKKKKKKK..............',
    '..............KKKKKKKKKKKKK.............',
    '..............KKKKKKKKKKKKK....K........',
    '..............KKKKKKKKKKKKK...KKKK......',
    '..............KKKKKKKKKKKKK....KKKK.....',
    '.............KKKKKKKKKKKKKKK.....KKK....',
    '............KKKKKKKKKKKKKKKKK.....KK....',
    '............KKKKKKKKKKKKKKKKK.....KK....',
    '...........KKKKKKKKKKKKKKKKKKK...KKK....',
    '...........KKKKKKKKKKKKKKKKKKK.KKKK.....',
    '...........KKKKKKKKKKKKKKKKKKKKKKKK.....',
    '...........KKKKKKKKKwKKKKKKKKKKKK.......',
    '...........KKKKKKKKKwKKKKKKKKKK.........',
    '............KKKKKKKKwKKKKKKKK...........',
    '...................KKK..................',
  ] },
  sit1e: { anchorX: 20, rows: [
    '........................................',
    '...............K........................',
    '...............K........................',
    '..............KIK.......................',
    '..............KIK.......................',
    '.............KKIKK.KKK..................',
    '.............KKIKKKKKKKKKKKKK...........',
    '............KKIIIKKKKKKKKKKKK...........',
    '............KKKKKKKKKKKKKKKK............',
    '............KKKEPEKKKKKEPEKKK...........',
    '........www.KKKEPEKKKKKEPEKKKwww........',
    '...........KKKKEEEKKKKKEEEKKKK..........',
    '.........ww.KKKKKKKKKKKKKKKKKww.........',
    '............KKKKKKKKNKKKKKKKK...........',
    '.............KKKKKKwKwKKKKKK............',
    '..............KKKKKKKKKKKKK.............',
    '...............KKKKKKKKKKK..............',
    '..............KKKKKKKKKKKKK.............',
    '..............KKKKKKKKKKKKK.............',
    '..............KKKKKKKKKKKKK....K........',
    '..............KKKKKKKKKKKKK...KKKK......',
    '..............KKKKKKKKKKKKK....KKKK.....',
    '.............KKKKKKKKKKKKKKK.....KKK....',
    '............KKKKKKKKKKKKKKKKK.....KK....',
    '............KKKKKKKKKKKKKKKKK.....KK....',
    '...........KKKKKKKKKKKKKKKKKKK...KKK....',
    '...........KKKKKKKKKKKKKKKKKKK.KKKK.....',
    '...........KKKKKKKKKKKKKKKKKKKKKKKK.....',
    '...........KKKKKKKKKwKKKKKKKKKKKK.......',
    '...........KKKKKKKKKwKKKKKKKKKK.........',
    '............KKKKKKKKwKKKKKKKK...........',
    '...................KKK..................',
  ] },
  groom0: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '...............K.........K..............',
    '...............K.........K..............',
    '..............KIK.......KIK.............',
    '..............KIK.......KIK.............',
    '.............KKIKK.KKK.KKIKK............',
    '.............KKIKKKKKKKKKIKK............',
    '............KKIIIKKKKKKKIIIKK...........',
    '............KKKKKKKKKKKKKKKKK...........',
    '............KKKKKKKKKKKKKKKKK...........',
    '........www.KKKwwwKKKKKwwwKKKwww........',
    '...........KKKKKKKKKKKKKKKKKKK..........',
    '.........ww.KKKKKKKKKKKKKKKKKww.........',
    '............KKKKKKKKNKKKKKKKK...........',
    '.............KKKKKKwKwKKKKKK............',
    '..............KKKKKKKKKKKKK....K........',
    '..............KKKKKKKKKKKKK...KKKK......',
    '..............KKKKKKKKKKKKK....KKKK.....',
    '.............KKKKKKKKKKKKKKK.....KKK....',
    '............KKKKKKKKKKKKKKKKK.....KK....',
    '............KKKKKKKKKKKKKKKKK.....KK....',
    '...........KKKKKKKKKKKKKKKKKKK...KKK....',
    '...........KKKKKKKKKKKKKKKKKKK.KKKK.....',
    '...........KKKKKKKKKKKKKKKKKKKKKKKK.....',
    '...........KKKKKKKKKwKKKKKKKKKKKK.......',
    '...........KKKKKKKKKwKKKKKKKKKK.........',
    '............KKKKKKKKwKKKKKKKK...........',
    '...................KKK..................',
  ] },
  groom1: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '...............K.........K..............',
    '...............K.........K..............',
    '..............KIK.......KIK.............',
    '..............KIK.......KIK.............',
    '.............KKIKK.KKK.KKIKK............',
    '.............KKIKKKKKKKKKIKK............',
    '............KKIIIKKKKKKKIIIKK...........',
    '............KKKKKKKKKKKKKKKKK...........',
    '............KKKKKKKKKKKKKKKKK...........',
    '........www.KKKwwwKKKKKwwwKKKwww........',
    '...........KKKKKKKKKKKKKKKKKKK..........',
    '.........ww.KKKKKKKKKKKKKKKKKww.........',
    '............KKKKKKKKNKKKKKKKK...........',
    '.............KKKKKKwKwKKKKKK...K........',
    '..............KKKKKKKKKKKKK...KKKK......',
    '..............KKKKKKKKKKKKK....KKKK.....',
    '.............KKKKKKKKKKKKKKK.....KKK....',
    '............KKKKKKKKKKKKKKKKK.....KK....',
    '............KKKKKKKKKKKKKKKKK.....KK....',
    '...........KKKKKKKKKKKKKKKKKKK...KKK....',
    '...........KKKKKKKKKKKKKKKKKKK.KKKK.....',
    '...........KKKKKKKKKKKKKKKKKKKKKKKK.....',
    '...........KKKKKKKKKwKKKKKKKKKKKK.......',
    '...........KKKKKKKKKwKKKKKKKKKK.........',
    '............KKKKKKKKwKKKKKKKK...........',
    '...................KKK..................',
  ] },
  stand0: { anchorX: 18, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '...............................K........',
    '..............................KKK.......',
    '...........................K..KIK.......',
    '..........................KKKKKIKK......',
    '......K...................KKKKKIKK......',
    '.....KK..................KKKKKKKKKK.....',
    '.....KK..................KKKKKKKKK......',
    '.....K...................KKKKKKKKK......',
    '....KK..................KKKKKKEPKKK.www.',
    '....KK..................KKKKKKEEKKKK....',
    '....KK..................KKKKKKKKKKKKN...',
    '....KK...................KKKKKKKKKKwww..',
    '....KK.....K............KKKKKKKKKKK.....',
    '....KK..KKKKKKK......KKKKKKKKKKK........',
    '....KKKKKKKKKKKKKKKKKKKKKKKKKK..........',
    '.....KKKKKKKKKKKKKKKKKKKKKKKKK..........',
    '.....KKKKKKKKKKKKKKKKKKKKKKKK...........',
    '......KKKKKKKKKKKKKKKKKKKKKKK...........',
    '......KKKKKKKKKKKKKKKKKKKKKK............',
    '......KKKKKKKKKKKKKKKKKKKKKK............',
    '.......KKKKKKKKKKKKKKKKKKKK.............',
    '........KKKKKKKKKKKKKKKKKK..............',
    '...........KS.KKK...SS.KKK..............',
    '...........SS.KKK...SS.KKK..............',
    '...........SS.KKK...SS.KKK..............',
    '...........SS.KKK...SS.KKK..............',
    '...........SSSKKKK..SSSKKKK.............',
    '........................................',
  ] },
  stand1: { anchorX: 18, rows: [
    '........................................',
    '........................................',
    '........................................',
    '...............................K........',
    '..............................KKK.......',
    '...........................K..KIK.......',
    '..........................KKKKKIKK......',
    '......K...................KKKKKIKK......',
    '.....KK..................KKKKKKKKKK.....',
    '.....KK..................KKKKKKKKK......',
    '.....K...................KKKKKKKKK......',
    '....KK..................KKKKKKEPKKK.www.',
    '....KK..................KKKKKKEEKKKK....',
    '....KK..................KKKKKKKKKKKKN...',
    '....KK...................KKKKKKKKKKwww..',
    '....KK.....K............KKKKKKKKKKK.....',
    '....KK..KKKKKKK......KKKKKKKKKKK........',
    '....KKKKKKKKKKKKKKKKKKKKKKKKKK..........',
    '.....KKKKKKKKKKKKKKKKKKKKKKKKK..........',
    '.....KKKKKKKKKKKKKKKKKKKKKKKK...........',
    '......KKKKKKKKKKKKKKKKKKKKKKK...........',
    '......KKKKKKKKKKKKKKKKKKKKKK............',
    '......KKKKKKKKKKKKKKKKKKKKKK............',
    '.......KKKKKKKKKKKKKKKKKKKK.............',
    '........KKKKKKKKKKKKKKKKKK..............',
    '...........KS.KKK...SS.KKK..............',
    '...........SS.KKK...SS.KKK..............',
    '...........SS.KKK...SS.KKK..............',
    '...........SS.KKK...SS.KKK..............',
    '...........SS.KKK...SS.KKK..............',
    '...........SSSKKKK..SSSKKKK.............',
    '........................................',
  ] },
  stand0e: { anchorX: 18, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '...........................K............',
    '..........................KKK...........',
    '......K...................KKKKKKKK......',
    '.....KK..................KKKKKKKKK......',
    '.....KK..................KKKKKKKKK......',
    '.....K...................KKKKKKKKK......',
    '....KK..................KKKKKKEPKKK.www.',
    '....KK..................KKKKKKEEKKKK....',
    '....KK..................KKKKKKKKKKKKN...',
    '....KK...................KKKKKKKKKKwww..',
    '....KK.....K............KKKKKKKKKKK.....',
    '....KK..KKKKKKK......KKKKKKKKKKK........',
    '....KKKKKKKKKKKKKKKKKKKKKKKKKK..........',
    '.....KKKKKKKKKKKKKKKKKKKKKKKKK..........',
    '.....KKKKKKKKKKKKKKKKKKKKKKKK...........',
    '......KKKKKKKKKKKKKKKKKKKKKKK...........',
    '......KKKKKKKKKKKKKKKKKKKKKK............',
    '......KKKKKKKKKKKKKKKKKKKKKK............',
    '.......KKKKKKKKKKKKKKKKKKKK.............',
    '........KKKKKKKKKKKKKKKKKK..............',
    '...........KS.KKK...SS.KKK..............',
    '...........SS.KKK...SS.KKK..............',
    '...........SS.KKK...SS.KKK..............',
    '...........SS.KKK...SS.KKK..............',
    '...........SSSKKKK..SSSKKKK.............',
    '........................................',
  ] },
  stand1e: { anchorX: 18, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '...........................K............',
    '..........................KKK...........',
    '......K...................KKKKKKKK......',
    '.....KK..................KKKKKKKKK......',
    '.....KK..................KKKKKKKKK......',
    '.....K...................KKKKKKKKK......',
    '....KK..................KKKKKKEPKKK.www.',
    '....KK..................KKKKKKEEKKKK....',
    '....KK..................KKKKKKKKKKKKN...',
    '....KK...................KKKKKKKKKKwww..',
    '....KK.....K............KKKKKKKKKKK.....',
    '....KK..KKKKKKK......KKKKKKKKKKK........',
    '....KKKKKKKKKKKKKKKKKKKKKKKKKK..........',
    '.....KKKKKKKKKKKKKKKKKKKKKKKKK..........',
    '.....KKKKKKKKKKKKKKKKKKKKKKKK...........',
    '......KKKKKKKKKKKKKKKKKKKKKKK...........',
    '......KKKKKKKKKKKKKKKKKKKKKK............',
    '......KKKKKKKKKKKKKKKKKKKKKK............',
    '.......KKKKKKKKKKKKKKKKKKKK.............',
    '........KKKKKKKKKKKKKKKKKK..............',
    '...........KS.KKK...SS.KKK..............',
    '...........SS.KKK...SS.KKK..............',
    '...........SS.KKK...SS.KKK..............',
    '...........SS.KKK...SS.KKK..............',
    '...........SS.KKK...SS.KKK..............',
    '...........SSSKKKK..SSSKKKK.............',
    '........................................',
  ] },
  stand0a: { anchorX: 18, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '................................K.......',
    '..........................K....KKK......',
    '..........................K....KIK......',
    '.........................KKK..KKIKK.....',
    '......K..................KKK..KKIKK.....',
    '.....KK.................KKKKKKKKKKKK....',
    '.....KK.................KKKKKKKKKK......',
    '.....K...................KKKKKKKKK......',
    '....KK...............ww.KEPKKKEPKKKwww..',
    '....KK..................KEEKKKEEKKK.....',
    '....KK..................KKKKKKKKKKK.....',
    '....KK...................KKKKNKKKK......',
    '....KK.....K............KKKKwKwKKK......',
    '....KK..KKKKKKK......KKKKKKKKKKK........',
    '....KKKKKKKKKKKKKKKKKKKKKKKKKK..........',
    '.....KKKKKKKKKKKKKKKKKKKKKKKKK..........',
    '.....KKKKKKKKKKKKKKKKKKKKKKKK...........',
    '......KKKKKKKKKKKKKKKKKKKKKKK...........',
    '......KKKKKKKKKKKKKKKKKKKKKK............',
    '......KKKKKKKKKKKKKKKKKKKKKK............',
    '.......KKKKKKKKKKKKKKKKKKKK.............',
    '........KKKKKKKKKKKKKKKKKK..............',
    '...........KS.KKK...SS.KKK..............',
    '...........SS.KKK...SS.KKK..............',
    '...........SS.KKK...SS.KKK..............',
    '...........SS.KKK...SS.KKK..............',
    '...........SSSKKKK..SSSKKKK.............',
    '........................................',
  ] },
  stand1a: { anchorX: 18, rows: [
    '........................................',
    '........................................',
    '........................................',
    '................................K.......',
    '..........................K....KKK......',
    '..........................K....KIK......',
    '.........................KKK..KKIKK.....',
    '......K..................KKK..KKIKK.....',
    '.....KK.................KKKKKKKKKKKK....',
    '.....KK.................KKKKKKKKKK......',
    '.....K...................KKKKKKKKK......',
    '....KK...............ww.KEPKKKEPKKKwww..',
    '....KK..................KEEKKKEEKKK.....',
    '....KK..................KKKKKKKKKKK.....',
    '....KK...................KKKKNKKKK......',
    '....KK.....K............KKKKwKwKKK......',
    '....KK..KKKKKKK......KKKKKKKKKKK........',
    '....KKKKKKKKKKKKKKKKKKKKKKKKKK..........',
    '.....KKKKKKKKKKKKKKKKKKKKKKKKK..........',
    '.....KKKKKKKKKKKKKKKKKKKKKKKK...........',
    '......KKKKKKKKKKKKKKKKKKKKKKK...........',
    '......KKKKKKKKKKKKKKKKKKKKKK............',
    '......KKKKKKKKKKKKKKKKKKKKKK............',
    '.......KKKKKKKKKKKKKKKKKKKK.............',
    '........KKKKKKKKKKKKKKKKKK..............',
    '...........KS.KKK...SS.KKK..............',
    '...........SS.KKK...SS.KKK..............',
    '...........SS.KKK...SS.KKK..............',
    '...........SS.KKK...SS.KKK..............',
    '...........SS.KKK...SS.KKK..............',
    '...........SSSKKKK..SSSKKKK.............',
    '........................................',
  ] },
  walk0: { anchorX: 18, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '...............................K........',
    '..............................KKK.......',
    '...........................K..KIK.......',
    '..........................KKKKKIKK......',
    '......K...................KKKKKIKK......',
    '.....KK..................KKKKKKKKKK.....',
    '.....KK..................KKKKKKKKK......',
    '.....K...................KKKKKKKKK......',
    '....KK..................KKKKKKEPKKK.www.',
    '....KK..................KKKKKKEEKKKK....',
    '....KK..................KKKKKKKKKKKKN...',
    '....KK...................KKKKKKKKKKwww..',
    '....KK.....K............KKKKKKKKKKK.....',
    '....KK..KKKKKKK......KKKKKKKKKKK........',
    '....KKKKKKKKKKKKKKKKKKKKKKKKKK..........',
    '.....KKKKKKKKKKKKKKKKKKKKKKKKK..........',
    '.....KKKKKKKKKKKKKKKKKKKKKKKK...........',
    '......KKKKKKKKKKKKKKKKKKKKKKK...........',
    '......KKKKKKKKKKKKKKKKKKKKKK............',
    '......KKKKKKKKKKKKKKKKKKKKKK............',
    '.......KKKKKKKKKKKKKKKKKKKK.............',
    '........KKKKKKKKKKKKKKKKKK..............',
    '...........KKKKKK.SSSS.KKKKK............',
    '............KKK...SS.....KKK............',
    '............KKK...SS.....KKK............',
    '............KKK...SS.....KKK............',
    '............KKKK..SSS....KKKK...........',
    '........................................',
  ] },
  walk1: { anchorX: 18, rows: [
    '........................................',
    '........................................',
    '........................................',
    '...............................K........',
    '..............................KKK.......',
    '...........................K..KIK.......',
    '..........................KKKKKIKK......',
    '........KK................KKKKKIKK......',
    '........K................KKKKKKKKKK.....',
    '.......KK................KKKKKKKKK......',
    '.......KK................KKKKKKKKK......',
    '......KK................KKKKKKEPKKK.www.',
    '......KK................KKKKKKEEKKKK....',
    '......KK................KKKKKKKKKKKKN...',
    '......KK.................KKKKKKKKKKwww..',
    '.....KKK...K............KKKKKKKKKKK.....',
    '.....KKKKKKKKKK......KKKKKKKKKKK........',
    '.....KKKKKKKKKKKKKKKKKKKKKKKKK..........',
    '......KKKKKKKKKKKKKKKKKKKKKKKK..........',
    '......KKKKKKKKKKKKKKKKKKKKKKK...........',
    '......KKKKKKKKKKKKKKKKKKKKKKK...........',
    '......KKKKKKKKKKKKKKKKKKKKKK............',
    '......KKKKKKKKKKKKKKKKKKKKKK............',
    '.......KKKKKKKKKKKKKKKKKKKK.............',
    '........KKKKKKKKKKKKKKKKKK..............',
    '...........KS.KKK...SS.KKK..............',
    '...........SS.KKK...SS.KKK..............',
    '...........SS.KKK...SS.KKK..............',
    '...........SS.KKKK..SSSKKK..............',
    '...........SS..........KKK..............',
    '...........SSS.........KKKK.............',
    '........................................',
  ] },
  walk2: { anchorX: 18, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '...............................K........',
    '..............................KKK.......',
    '...........................K..KIK.......',
    '..........................KKKKKIKK......',
    '......K...................KKKKKIKK......',
    '.....KK..................KKKKKKKKKK.....',
    '.....KK..................KKKKKKKKK......',
    '.....K...................KKKKKKKKK......',
    '....KK..................KKKKKKEPKKK.www.',
    '....KK..................KKKKKKEEKKKK....',
    '....KK..................KKKKKKKKKKKKN...',
    '....KK...................KKKKKKKKKKwww..',
    '....KK.....K............KKKKKKKKKKK.....',
    '....KK..KKKKKKK......KKKKKKKKKKK........',
    '....KKKKKKKKKKKKKKKKKKKKKKKKKK..........',
    '.....KKKKKKKKKKKKKKKKKKKKKKKKK..........',
    '.....KKKKKKKKKKKKKKKKKKKKKKKK...........',
    '......KKKKKKKKKKKKKKKKKKKKKKK...........',
    '......KKKKKKKKKKKKKKKKKKKKKK............',
    '......KKKKKKKKKKKKKKKKKKKKKK............',
    '.......KKKKKKKKKKKKKKKKKKKK.............',
    '........KKKKKKKKKKKKKKKKKK..............',
    '.........SSKS.KKKKK.SKKKKK..............',
    '.........SS.....KKK..KKK................',
    '.........SS.....KKK..KKK................',
    '.........SS.....KKK..KKK................',
    '.........SSS....KKKK.KKKK...............',
    '........................................',
  ] },
  walk3: { anchorX: 18, rows: [
    '........................................',
    '........................................',
    '........................................',
    '...............................K........',
    '..............................KKK.......',
    '...........................K..KIK.......',
    '..........................KKKKKIKK......',
    '...K......................KKKKKIKK......',
    '...K.....................KKKKKKKKKK.....',
    '..KK.....................KKKKKKKKK......',
    '..KK.....................KKKKKKKKK......',
    '..KK....................KKKKKKEPKKK.www.',
    '..KK....................KKKKKKEEKKKK....',
    '..KK....................KKKKKKKKKKKKN...',
    '..KK.....................KKKKKKKKKKwww..',
    '..KKK......K............KKKKKKKKKKK.....',
    '...KK...KKKKKKK......KKKKKKKKKKK........',
    '...KKK.KKKKKKKKKKKKKKKKKKKKKKK..........',
    '....KKKKKKKKKKKKKKKKKKKKKKKKKK..........',
    '....KKKKKKKKKKKKKKKKKKKKKKKKK...........',
    '.....KKKKKKKKKKKKKKKKKKKKKKKK...........',
    '......KKKKKKKKKKKKKKKKKKKKKK............',
    '......KKKKKKKKKKKKKKKKKKKKKK............',
    '.......KKKKKKKKKKKKKKKKKKKK.............',
    '........KKKKKKKKKKKKKKKKKK..............',
    '...........KS.KKK...SS.KKK..............',
    '...........SS.KKK...SS.KKK..............',
    '...........SS.KKK...SS.KKK..............',
    '...........SSSKKK...SS.KKKK.............',
    '..............KKK...SS..................',
    '..............KKKK..SSS.................',
    '........................................',
  ] },
  sleep0: { anchorX: 18, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '....K....................K.....K........',
    '...KKK.......KKK.........K.....K........',
    '...KK....KKKKKKKKKKK....KwK...KKK.......',
    '...KK..KKKKKKKKKKKKKKK..wKK.K.KKK.......',
    '...KK.KKKKKKKKKKKKKKKKKwKKKKKKKKKK......',
    '...KKKKKKKKKKKKKKKKKKKKwKKKKKKKKKK......',
    '....KKKKKKKKKKKKKKKKKKKwKKKKKKKKK.......',
    '.....KKKKKKKKKKKKKKKKKKwKKwwwKKwwK......',
    '.....KKKKKKKKKKKKKKKKKKKwKKKKKKKKN......',
    '.....KKKKKKKKKKKKKKKKKKKKwKKKKKKK.......',
    '......KKKKKKKKKKKKKKKKK..KKKKKwKK.......',
    '.............KKK............K...........',
  ] },
  sleep1: { anchorX: 18, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '....K........KKK........................',
    '...KKK...KKKKKKKKKKK.....K.....K........',
    '...KK..KKKKKKKKKKKKKKK...K.....K........',
    '...KK.KKKKKKKKKKKKKKKKK.KwK...KKK.......',
    '...KKKKKKKKKKKKKKKKKKKKKwKK.K.KKK.......',
    '...KKKKKKKKKKKKKKKKKKKKwKKKKKKKKKK......',
    '...KKKKKKKKKKKKKKKKKKKKwKKKKKKKKKK......',
    '....KKKKKKKKKKKKKKKKKKKwKKKKKKKKK.......',
    '.....KKKKKKKKKKKKKKKKKKwKKwwwKKwwK......',
    '.....KKKKKKKKKKKKKKKKKKKwKKKKKKKKN......',
    '.....KKKKKKKKKKKKKKKKKKKKwKKKKKKK.......',
    '......KKKKKKKKKKKKKKKKK..KKKKKwKK.......',
    '.............KKK............K...........',
  ] },
  stretch0: { anchorX: 18, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........K...............................',
    '.......KK...............................',
    '.......KK...............................',
    '.......K................................',
    '......KK................................',
    '......KK................................',
    '......KK................................',
    '......KK................................',
    '......KK................................',
    '......KKK...............................',
    '.......KK.KKKKK...........K.....K.......',
    '.......KKKKKKKKKK.........K.....K.......',
    '.......KKKKKKKKKKKK......KKK...KIK......',
    '.......KKKKKKKKKKKKKK....KKK...KIK......',
    '.......KKKKKKKKKKKKKKKK.KKKKKKKKIKK.....',
    '.......KKKKKKKKKKKKKKKKKKKKKKKKKKKK.....',
    '........KKKKKKKKKKKKKKKKKKKKKKKKKK......',
    '........KKKKKKKKKKKKKKKKKwwwKKKKwww.....',
    '.........SKKKKKKKKKKKKKKKKKKKKKKKKN.....',
    '.........SSSKKK.KKKKKKKKKKKKKKKKK.......',
    '.........SSSKKK.....KKKKKKKKKKKK........',
    '.........SSSKKK.......KKKKKKKK..........',
    '.........SSSKKK..........KKKKK..........',
    '.........SSSKKK.............KKKKKK......',
    '.........SSSKKKKK...........KKKKKK......',
    '........................................',
  ] },
  stretch1: { anchorX: 18, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........K...............................',
    '.......KK...............................',
    '.......KK...............................',
    '.......K................................',
    '......KK................................',
    '......KK................................',
    '......KK................................',
    '......KK................................',
    '......KK................................',
    '......KKK...............................',
    '.......KK.KKKKK.........................',
    '.......KKKKKKKKKK.......................',
    '.......KKKKKKKKKK.......................',
    '.......KKKKKKKKKKK......................',
    '.......KKKKKKKKKKKK.......K.....K.......',
    '.......KKKKKKKKKKKKKK.....K.....K.......',
    '........KKKKKKKKKKKKKK...KKK...KIK......',
    '........KKKKKKKKKKKKKKK..KKK...KIK......',
    '.........SKKKKKKKKKKKKKKKKKKKKKKIKK.....',
    '.........SSSKKKKKKKKKKKKKKKKKKKKKKK.....',
    '.........SSSKKKKKKKKKKKKKKKKKKKKKK......',
    '.........SSSKKK.KKKKKKKKKwwwKKKKwww.....',
    '.........SSSKKK...KKKKKKKKKKKKKKKKN.....',
    '.........SSSKKK.....KKKKKKKKKKKKK.......',
    '.........SSSKKK......KKKKKKKKKKK........',
    '.........SSSKKK.......KKKKKKKKKKKKKK....',
    '.........SSSKKKKK........KKKKKKKKKKK....',
    '........................................',
  ] },
  stretch2: { anchorX: 18, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........K...............................',
    '.......KK...............................',
    '.......KK...............................',
    '.......K................................',
    '......KK................................',
    '......KK................................',
    '......KK................................',
    '......KK................................',
    '......KK................................',
    '......KKK...............................',
    '.......KK.KKKKK.........................',
    '.......KKKKKKKKKK.......................',
    '.......KKKKKKKKKK.......................',
    '.......KKKKKKKKKKK......................',
    '.......KKKKKKKKKKKK.....................',
    '.......KKKKKKKKKKKKK....................',
    '........KKKKKKKKKKKK......K.....K.......',
    '........KKKKKKKKKKKKK.....K.....K.......',
    '.........SKKKKKKKKKKKK...KKK...KIK......',
    '.........SSSKKKKKKKKKKK..KKK...KIK......',
    '.........SSSKKKKKKKKKKKKKKKKKKKKIKK.....',
    '.........SSSKKKKKKKKKKKKKKKKKKKKKKK.....',
    '.........SSSKKKKKKKKKKKKKKKKKKKKKK......',
    '.........SSSKKK..KKKKKKKKwwwKKKKwww.....',
    '.........SSSKKK....KKKKKKKKKKKKKKKN.....',
    '.........SSSKKK......KKKKKKKKKKKK.......',
    '.........SSSKKK......KKKKKKKKKKKKKKKK...',
    '.........SSSKKKKK.....KKKKKKKKKKKKKKK...',
    '.........................KKKKKKKK.......',
  ] },
  jump0: { anchorX: 18, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '................................K.......',
    '..........................K....KKK......',
    '..........................K....KIK......',
    '.........................KKK..KKIKK.....',
    '.........................KKK..KKIKK.....',
    '........................KKKKKKKKKKKK....',
    '........................KKKKKKKKKK......',
    '.........................KKKKKKKKK......',
    '...K................www.KEPKKKEPKKK.www.',
    '...K....................KEEKKKEEKKK.....',
    '...KK...................KKKKKKKKKKK.....',
    '...KK....................KKKKNKKKK......',
    '...KKK....KKKKK.........KKKKwKwKKK......',
    '....KKK.KKKKKKKKK....KKKKKKKKKKK........',
    '.....KKKKKKKKKKKKKKKKKKKKKKKKKK.........',
    '......KKKKKKKKKKKKKKKKKKKKKKKK..........',
    '......KKKKKKKKKKKKKKKKKKKKKKKK..........',
    '.......KKKKKKKKKKKKKKKKKKKKKK...........',
    '.......KKKKKKKKKKKKKKKKKKKKKK...........',
    '........KKKKKKKKKKKKKKKKKKKKK...........',
    '........KKKKKKKKKKKKKKKKKKKKK...........',
    '.........KKKKKKKKKKKKKKKKKKK............',
    '........................................',
  ] },
  jump1: { anchorX: 18, rows: [
    '........................................',
    '........................................',
    '................................K.......',
    '..........................K....KKK......',
    '..........................K....KIK......',
    '.........................KKK..KKIKK.....',
    '.......K.................KKK..KKIKK.....',
    '......KK................KKKKKKKKKKKK....',
    '......KK................KKKKKKKKKK......',
    '......K..................KKKKKKKKK......',
    '.....KK.............www.KEPKKKEPKKK.www.',
    '.....KK.................KEPKKKEPKKK.....',
    '.....KK.................KKKKKKKKKKK.....',
    '.....KK....K............KKKKKNKKKK......',
    '.....KK.KKKKKKK......KKKKKKKwKwKKK......',
    '.....KKKKKKKKKKK....KKKKKKKKKKKK........',
    '......KKKKKKKKKKKKKKKKKKKKKKKK..........',
    '......KKKKKKKKKKKKKKKKKKKKKKK...........',
    '......KKKKKKKKKKKKKKKKKKKKKKK...........',
    '......KKKKKKKKKKKKKKKKKKKKKK............',
    '......KKKKKKKKKKKKKKKKKKKKKK............',
    '.......KKKKKKKKKKKKKKKKKKKK.............',
    '........KKKKKKKKKKKKKKKKKK..............',
    '.........KKKK.......KKKK................',
    '.........KKKK.......KKKK................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
  ] },
  jump2: { anchorX: 18, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '.................................K......',
    '...........................K....KKK.....',
    '...........................K....KIK.....',
    '..........................KKK..KKIKK....',
    '..........................KKK..KKIKK....',
    '.........................KKKKKKKKKKKK...',
    '.........................KKKKKKKKKK.....',
    '..........................KKKKKKKKK.....',
    '..K..................www.KEPKKKEPKKK.www',
    '..KK.....................KEEKKKEEKKK....',
    '..KK.....................KKKKKKKKKKK....',
    '...KK....KKKKKKK.......KKKKKKKNKKKK.....',
    '....KKKKKKKKKKKKKK...KKKKKKKKwKwKKK.....',
    '.....KKKKKKKKKKKKKKKKKKKKKKKKKKKK.......',
    '......KKKKKKKKKKKKKKKKKKKKKKKKK.........',
    '......KKKKKKKKKKKKKKKKKKKKKKKKK.........',
    '.......KKKKKKKKKKKKKKKKKKKKKKK..........',
    '........KKKKKKKKKKKKKKKKKKKKK...........',
    '........................................',
  ] },
  scruff0: { anchorX: 20, rows: [
    '........................................',
    '...............K.........K..............',
    '..............KKK.......KKK.............',
    '..............KIK...K...KIK.............',
    '.............KKIKKKKKKKKKIKK............',
    '.............KKIKKKKKKKKKIKK............',
    '............KKKKKKKKKKKKKKKKK...........',
    '..............KKKKKKKKKKKKK.............',
    '.............KKEPEKKKKKEPEKK............',
    '...........wwwKKKKKKKKKKKKKwww..........',
    '..............KKKKKKKKKKKKK.............',
    '...............KKKKKNKKKKK..............',
    '................KKKKKKKKK...............',
    '...............KKKKKKKKK................',
    '...............KKKKKKKKK................',
    '...............KKKKKKKKK................',
    '..............KKKKKKKKKKK...............',
    '..............KKKKKKKKKKK...............',
    '..............KKKKKKKKKKK...............',
    '...............KKKKKKKKK................',
    '...............KKKKKKKKKK...............',
    '...............KKKKKKKKKKK..............',
    '..............KKKKKKKKKKKKK.............',
    '.............KKKKKKKKKKKKKK.............',
    '.............KKK.KKKKKKKKKKK............',
    '............KKK..KK.KKK.KKKK............',
    '............KKK..KK.KKK..KKK............',
    '............KK...KK..KK..KKK............',
    '...........KKK...KK.KKK..KK.............',
    '............K....KKKKKK..K..............',
    '.................KKK.K..................',
    '..................K.....................',
  ] },
  scruff1: { anchorX: 20, rows: [
    '........................................',
    '...............K.........K..............',
    '..............KKK.......KKK.............',
    '..............KIK...K...KIK.............',
    '.............KKIKKKKKKKKKIKK............',
    '.............KKIKKKKKKKKKIKK............',
    '............KKKKKKKKKKKKKKKKK...........',
    '..............KKKKKKKKKKKKK.............',
    '.............KKEPEKKKKKEPEKK............',
    '...........wwwKKKKKKKKKKKKKwww..........',
    '..............KKKKKKKKKKKKK.............',
    '...............KKKKKNKKKKK..............',
    '................KKKKKKKKK...............',
    '.................KKKKKKKKK..............',
    '.................KKKKKKKKK..............',
    '.................KKKKKKKKK..............',
    '................KKKKKKKKKKK.............',
    '................KKKKKKKKKKK.............',
    '................KKKKKKKKKKK.............',
    '.................KKKKKKKKK..............',
    '.................KKKKKKKKKK.............',
    '.................KKKKKKKKKKK............',
    '................KKKKKKKKKKKKK...........',
    '...............KKKKKKKKKKKKKK...........',
    '...............KKK.KKKKKKKKKKK..........',
    '..............KKK..KK.KKK.KKKK..........',
    '..............KKK..KK.KKK..KKK..........',
    '..............KK...KK..KK..KKK..........',
    '.............KKK...KK.KKK..KK...........',
    '..............K....KKKKKK..K............',
    '...................KKK.K................',
    '....................K...................',
  ] },
  startle0: { anchorX: 18, rows: [
    '........................................',
    '........................................',
    '........................................',
    '.......K................................',
    '......KKK...............................',
    '.....KKKKK..............................',
    '.....KKKKK..............................',
    '.....KKKK...............................',
    '....KKKKK...............................',
    '....KKKKK...............................',
    '....KKKKK...............................',
    '....KKKKK...............................',
    '....KKKKK...............................',
    '....KKKKK...............................',
    '....KKKKK...............................',
    '....KKKKK.............KKKKKKKKKKKKK.....',
    '....KKKKK.......KKKKK.KKKKKKKKKKKKK.....',
    '.....KKKKK...KKKKKKKKKKKEEEKKKEEEK......',
    '.....KKKKK..KKKKKKKKKKKKEPEKKKEPEK......',
    '.....KKKKKKKKKKKKKKwwKKKEPEKKKEPEKwww...',
    '......KKKKKKKKKKKKKKKKKKKKKKKKKKKK......',
    '......KKKKKKKKKKKKKKKKKKKKKKKKKKKK......',
    '.......KKKKKKKKKKKKKKKKKKKKKNKKKK.......',
    '.......KKKKKKKKK.....KKKKKKKKKK.........',
    '........KKKKK.KKK....KKKKKKK............',
    '.........KKKK.KKK....KKK.KKK............',
    '.........KKKK.KKK....KKK.KKK............',
    '..........KKK.KKK....KKK.KKK............',
    '..........KKK.KKK....KKK.KKK............',
    '..........KKK.KKK....KKK.KKK............',
    '..........KKK.KKK....KKK.KKK............',
    '........................................',
  ] },
  run0: { anchorX: 18, rows: [
    '........................................',
    '........................................',
    '...............................K........',
    '..............................KKK.......',
    '...........................K..KIK.......',
    '..........................KKKKKIKK......',
    '..........................KKKKKIKK......',
    '.........................KKKKKKKKKK.....',
    '.........................KKKKKKKKK......',
    '....K....................KKKKKKKKK......',
    '...KK...................KKKKKKEPKKK.www.',
    '...KK...................KKKKKKEEKKKK....',
    '...KK...................KKKKKKKKKKKKN...',
    '...KK....................KKKKKKKKKKK....',
    '...KK...................KKKKKKKKKKK.....',
    '...KK...KKKKKKK.......KKKKKKKKKK........',
    '...KK..KKKKKKKKKKKKKKKKKKKKKKK..........',
    '...KKKKKKKKKKKKKKKKKKKKKKKKKKK..........',
    '....KKKKKKKKKKKKKKKKKKKKKKKKK...........',
    '.....KKKKKKKKKKKKKKKKKKKKKKKK...........',
    '......KKKKKKKKKKKKKKKKKKKKKK............',
    '......KKKKKKKKKKKKKKKKKKKKKK............',
    '.......KKKKKKKKKKKKKKKKKKKK.............',
    '........KKKKKKKKKKKKK.KKKKK.............',
    '...........KKKK........SKKK.............',
    '............KKKK.......SKKK.............',
    '.............KKKK......SSKK.............',
    '.............SKKKK.....SSKK.............',
    '.............SSSKKK...SSKKK.............',
    '.............SSS.K....SS.K..............',
    '.............SSS.....SSS................',
    '..............S.......S.................',
  ] },
  run1: { anchorX: 18, rows: [
    '...............................K........',
    '..............................KKK.......',
    '...........................K..KIK.......',
    '..........................KKKKKIKK......',
    '..........................KKKKKIKK......',
    '.........................KKKKKKKKKK.....',
    '.........................KKKKKKKKK......',
    '....K....................KKKKKKKKK......',
    '...KK...................KKKKKKEPKKK.www.',
    '...KK...................KKKKKKEEKKKK....',
    '...KK...................KKKKKKKKKKKKN...',
    '...KK....................KKKKKKKKKKK....',
    '...KK...................KKKKKKKKKKK.....',
    '...KK...KKKKKKK.......KKKKKKKKKK........',
    '...KK..KKKKKKKKKKKKKKKKKKKKKKK..........',
    '...KKKKKKKKKKKKKKKKKKKKKKKKKKK..........',
    '....KKKKKKKKKKKKKKKKKKKKKKKKK...........',
    '.....KKKKKKKKKKKKKKKKKKKKKKKK...........',
    '......KKKKKKKKKKKKKKKKKKKKKK............',
    '......KKKKKKKKKKKKKKKKKKKKKK............',
    '.......KKKKKKKKKKKKKKKKKKKK.............',
    '........KKKKKKKKKKKKKKKKKKK.............',
    '.........KKKKS.........SKKKKK...........',
    '....KKKKKKKKSS..........SSKKKKKKK.......',
    '...KKKKKKKSSS............SSSKKKKKK......',
    '....KK.SSSSS..............SSSS..K.......',
    '......SSSS..................SSS.........',
    '.......S.....................S..........',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
  ] },
  run2: { anchorX: 18, rows: [
    '........................................',
    '........................................',
    '........................................',
    '...............................K........',
    '..............................KKK.......',
    '...........................K..KIK.......',
    '..........................KKKKKIKK......',
    '..........................KKKKKIKK......',
    '.........................KKKKKKKKKK.....',
    '.........................KKKKKKKKK......',
    '....K....................KKKKKKKKK......',
    '...KK...................KKKKKKEPKKK.www.',
    '...KK...................KKKKKKEEKKKK....',
    '...KK...................KKKKKKKKKKKKN...',
    '...KK....................KKKKKKKKKKK....',
    '...KK...................KKKKKKKKKKK.....',
    '...KK...KKKKKKK.......KKKKKKKKKK........',
    '...KK..KKKKKKKKKKKKKKKKKKKKKKK..........',
    '...KKKKKKKKKKKKKKKKKKKKKKKKKKK..........',
    '....KKKKKKKKKKKKKKKKKKKKKKKKK...........',
    '.....KKKKKKKKKKKKKKKKKKKKKKKK...........',
    '......KKKKKKKKKKKKKKKKKKKKKK............',
    '......KKKKKKKKKKKKKKKKKKKKKK............',
    '.......KKKKKKKKKKKKKKKKKKKK.............',
    '........KKKKKKKKKKKKK.KKKKK.............',
    '...........KKKK........SKKK.............',
    '............KKKK........SKKK............',
    '...........SSSK.........SSKKK...........',
    '..........SSS............SSKK...........',
    '...........S.............SSKKK..........',
    '.........................SSSKKK.........',
    '..........................S..K..........',
  ] },
  run3: { anchorX: 18, rows: [
    '........................................',
    '...............................K........',
    '..............................KKK.......',
    '...........................K..KIK.......',
    '..........................KKKKKIKK......',
    '..........................KKKKKIKK......',
    '.........................KKKKKKKKKK.....',
    '.........................KKKKKKKKK......',
    '....K....................KKKKKKKKK......',
    '...KK...................KKKKKKEPKKK.www.',
    '...KK...................KKKKKKEEKKKK....',
    '...KK...................KKKKKKKKKKKKN...',
    '...KK....................KKKKKKKKKKK....',
    '...KK...................KKKKKKKKKKK.....',
    '...KK...KKKKKKK.......KKKKKKKKKK........',
    '...KK..KKKKKKKKKKKKKKKKKKKKKKK..........',
    '...KKKKKKKKKKKKKKKKKKKKKKKKKKK..........',
    '....KKKKKKKKKKKKKKKKKKKKKKKKK...........',
    '.....KKKKKKKKKKKKKKKKKKKKKKKK...........',
    '......KKKKKKKKKKKKKKKKKKKKKK............',
    '......KKKKKKKKKKKKKKKKKKKKKK............',
    '.......KKKKKKKKKKKKKKKKKKKK.............',
    '........KKKKKKKKKKKKK.KKKKK.............',
    '..........KKKS.........SKKK.............',
    '..........KKKS.........SSKKK............',
    '.........KKKSS..........SSKKK...........',
    '........KKKKS...........SS.K............',
    '.......KKKKS...........SSS..............',
    '......KKKKS.............S...............',
    '.....KKKKS..............................',
    '....KKK.S...............................',
    '.....K..................................',
  ] },
  roll0: { anchorX: 16, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '.....................KKK...K.KKKK.......',
    '....K...............KKKK..KKKKKKKK......',
    '...KK...........SSKKKKK..SKKKK.KIK......',
    '...KK.........SSSKKKK.SSSKKKKKKKIKK.....',
    '...KK......SSSSKKKKKSSSSKKKKKKKKKKK.....',
    '...KKK....SSSSKKKKKSSSSKwKKKKKKKKK......',
    '....KKK.KKKSKKKKKKKKSKKKwKKKKKEPKK......',
    '....KKKKKKKKKKKKKKKKKKKKwKKKKKEEKKwww...',
    '.....KKKKKKKKKKKKKKKKKKKKKKKKKKKKKN.....',
    '.......KKKKKKKKKKKKKKKKKKwKKKKKKKK......',
    '.........KKKKKKKKKKKKKKKKK.KKKKK........',
    '........................................',
  ] },
  roll1: { anchorX: 16, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '..................KKK.....KKK...........',
    '..................KKK..SSSKKK...........',
    '..............SS.KKK...SSSKK............',
    '..............SSSKK....SSKKK....K.......',
    '....K........SSSKKK...SS.KKKK..KKK......',
    '...KK........SS.KK...SSS.KKKK..KIK......',
    '...KK.......SS.KKK..SSS.KKKKKKKKIKK.....',
    '...KK......SSSKKKKKKSSS.KKKKKKKKKKK.....',
    '...KKK....SSSKKKKKKSSSKKwKKKKKKKKK......',
    '....KKK.KKKSKKKKKKKKSKKKwKKKKKEPKK......',
    '....KKKKKKKKKKKKKKKKKKKKwKKKKKEEKKwww...',
    '.....KKKKKKKKKKKKKKKKKKKKKKKKKKKKKN.....',
    '.......KKKKKKKKKKKKKKKKKKwKKKKKKKK......',
    '.........KKKKKKKKKKKKKKKKK.KKKKK........',
    '........................................',
  ] },
  roll2: { anchorX: 16, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '.............KKK.....SK.................',
    '.............KKK....SKKK................',
    '............SSKK....SKKK................',
    '............SSKK....SSKK................',
    '............SSKK....SSKK................',
    '....K......SSSKK....SSKK................',
    '...KK......SS.KK....SSKKK...............',
    '...KK......SS.KK....SS.KK...............',
    '...KK......SSKKKKKKSSS.KKw.KKKNK........',
    '...KKK....SSSKKKKKKSSSKKwKKKKKKKKK......',
    '....KKK.KKKSKKKKKKKKSKKKwKKKKKKKKK......',
    '....KKKKKKKKKKKKKKKKKKKKwKKwwwKwww......',
    '.....KKKKKKKKKKKKKKKKKKKKKKKKKKKKK......',
    '.......KKKKKKKKKKKKKKKKKKwKKKKKKKK......',
    '.........KKKKKKKKKKKKKKKKKKKKKKKKKK.....',
    '.........................KKKKKKKKKK.....',
  ] },
  roll3: { anchorX: 16, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '..................KKK.....KKK...........',
    '..................KKK..SSSKKK...........',
    '..............SS.KKK...SSSKK............',
    '..............SSSKK....SSKKK....K.......',
    '....K........SSSKKK...SS.KKKK..KKK......',
    '...KK........SS.KK...SSS.KKKK..KIK......',
    '...KK.......SS.KKK..SSS.KKKKKKKKIKK.....',
    '...KK......SSSKKKKKKSSS.KKKKKKKKKKK.....',
    '...KKK....SSSKKKKKKSSSKKwKKKKKKKKK......',
    '....KKK.KKKSKKKKKKKKSKKKwKKKKKEPKK......',
    '....KKKKKKKKKKKKKKKKKKKKwKKKKKEEKKwww...',
    '.....KKKKKKKKKKKKKKKKKKKKKKKKKKKKKN.....',
    '.......KKKKKKKKKKKKKKKKKKwKKKKKKKK......',
    '.........KKKKKKKKKKKKKKKKK.KKKKK........',
    '........................................',
  ] },
  pounce0: { anchorX: 18, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '......K.................................',
    '.....KK.................................',
    '.....KK.................................',
    '.....KK..........................K......',
    '.....K......................K...KKK.....',
    '.....K.....................KKK..KIK.....',
    '.....KK..KKKKKKK...........KKK.KKIKK....',
    '.....KK.KKKKKKKKK.........KKKKKKKKKK....',
    '.....KKKKKKKKKKKKK........KKKKKKKKK.....',
    '.....KKKKKKKKKKKKK.........KKKKKKKKK....',
    '......KKKKKKKKKKKK.........KKKKKEPKK....',
    '.......KKKKKKKKKKKKKKK....KKKKKKEEKKK...',
    '.......KKKKKKKKKKKKKKKKKK..KKKKKKKKKN...',
    '........KKKKKKKKKKKKKKKKKKKKKKKKKKKK....',
    '.........KKKKKKKKKKKKKKKKKKKKKKKKKK.....',
    '.........KKKKKKKKKKKKKKKKKKKKKKK........',
    '.........KKKKKKKKKKKKKKKKKKKKKK.........',
    '.........KKKKKKK.KKKKKKKKKKKKK..........',
    '.........KKKKKKK......KKKKKKKK..........',
    '.........KKKKKKK.......KKKKKKK..........',
    '........................................',
  ] },
  pounce1: { anchorX: 18, rows: [
    '........................................',
    '........................................',
    '..............................K.........',
    '.........................K...KKK........',
    '........................KKK..KIK........',
    '......K.................KKK.KKIKK.......',
    '.....KK................KKKKKKKKKK.......',
    '.....K.................KKKKKKKKK........',
    '....KK..................KKKKKKKKK.......',
    '....KK..................KKKKKEPKKwww....',
    '....KK.................KKKKKKEEKKK......',
    '....KK..................KKKKKKKKKN......',
    '....KK...KKKKK.........KKKKKKKKKK.......',
    '....KK.KKKKKKKKKKKKKKKKKKKKKKKKK........',
    '....KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK.....',
    '.....KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK....',
    '.....KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK.....',
    '......KKKKKKKKKKKKKKKKKSKKKSSSSSSS......',
    '.......KKKKSKKKKKKKKKKKKSSSSSSSSSSS.....',
    '.......KKKSKKKKKKKKKKKKKKKKK.....S......',
    '.........SKKKK..KKKKK...K...............',
    '.......SSKKKK...........................',
    '......SSSKKK............................',
    '.....SSSKKK.............................',
    '....SSSKKK..............................',
    '.....S.KKK..............................',
    '......KKK...............................',
    '.......K................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
  ] },
  pounce2: { anchorX: 18, rows: [
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '........................................',
    '.......K................................',
    '......KK................................',
    '......K.................................',
    '.....KK.................................',
    '.....KK..........................K......',
    '.....KK.....................K...KKK.....',
    '.....KK....................KKK..KIK.....',
    '.....KK..KKKKKKK...........KKK.KKIKK....',
    '.....KKKKKKKKKKKK.........KKKKKKKKKK....',
    '......KKKKKKKKKKKK........KKKKKKKKK.....',
    '......KKKKKKKKKKKK.........KKKKKKKKK....',
    '.......KKKKKKKKKKK.........KKKKKEPKK....',
    '.......KKKKKKKKKKKKKKKK...KKKKKKEEKKK...',
    '.......KKKKKKKKKKKKKKKKKKK.KKKKKKKKKN...',
    '........KKKKKKKKKKKKKKKKKKKKKKKKKKKK....',
    '.........KKKKKKKKKKKKKKKKKKKKKKKKKK.....',
    '.........KKKKKKKKKKKKKKKKKKKKKKK........',
    '.........KKKKKKKKKKKKKKKKSKKKKK.........',
    '.........KKKKKKKKKKKKKKKSKKKKK..........',
    '.........KKKKKKK......KKKSKKKKK.........',
    '.........KKKKKKK........KKSKKKKKKK......',
    '.........KKKKKKK............SKKKKKK.....',
    '...............................S.K......',
  ] },
  paw0: { anchorX: 20, rows: [
    '........................................',
    '........................................',
    '...............K.........K..............',
    '...............K.........K..............',
    '..............KIK.......KIK.............',
    '..............KIK.......KIK.............',
    '.............KKIKK.KKK.KKIKK............',
    '.............KKIKKKKKKKKKIKK............',
    '............KKIIIKKKKKKKIIIKK...........',
    '............KKKKKKKKKKKKKKKKK...........',
    '............KKKEPEKKKKKEPEKKK...........',
    '........www.KKKEPEKKKKKEPEKKKwww........',
    '...........KKKKEEEKKKKKEEEKKKK..........',
    '.........ww.KKKKKKKKKKKKKKKKKww.........',
    '............KKKKKKKKNKKKKKKKK...........',
    '.............KKKKKKwKwKKKKKK............',
    '..............KKKKKKKKKKKKK.............',
    '...............KKKKKKKKKKK..............',
    '..............KKKKKKKKKKKKK.............',
    '..............KKKKKKKKKKKKK....K........',
    '.........K....KKKKKKKKKKKKK...KKKK......',
    '........KwK...KKKKKKKKKKKKK....KKKK.....',
    '.......KKKKK.KKKKKKKKKKKKKKK.....KKK....',
    '........KKKKKKKKKKKKKKKKKKKKK.....KK....',
    '.........KKKKKKKKKKKKKKKKKKKK.....KK....',
    '...........KKKKKKKKKKKKKKKKKKK...KKK....',
    '...........KKKKKKKKKKKKKKKKKKK.KKKK.....',
    '...........KKKKKKKKKKKKKKKKKKKKKKKK.....',
    '...........KKKKKKKKKwKKKKKKKKKKKK.......',
    '...........KKKKKKKKKwKKKKKKKKKK.........',
    '............KKKKKKKKwKKKKKKKK...........',
    '...................KKK..................',
  ] },
  paw1: { anchorX: 20, rows: [
    '........................................',
    '...............K.........K..............',
    '...............K.........K..............',
    '..............KIK.......KIK.............',
    '..............KIK.......KIK.............',
    '.............KKIKK.KKK.KKIKK............',
    '.............KKIKKKKKKKKKIKK............',
    '............KKIIIKKKKKKKIIIKK...........',
    '............KKKKKKKKKKKKKKKKK...........',
    '............KKKEPEKKKKKEPEKKK...........',
    '........www.KKKEPEKKKKKEPEKKKwww........',
    '...........KKKKEEEKKKKKEEEKKKK..........',
    '.........ww.KKKKKKKKKKKKKKKKKww.........',
    '............KKKKKKKKNKKKKKKKK...........',
    '.............KKKKKKwKwKKKKKK............',
    '..............KKKKKKKKKKKKK.............',
    '...............KKKKKKKKKKK..............',
    '.....K........KKKKKKKKKKKKK.............',
    '....KwK.......KKKKKKKKKKKKK.............',
    '...KKKKK......KKKKKKKKKKKKK....K........',
    '....KKKKKKK...KKKKKKKKKKKKK...KKKK......',
    '.....KKKKKKKK.KKKKKKKKKKKKK....KKKK.....',
    '.......KKKKKKKKKKKKKKKKKKKKK.....KKK....',
    '.........KKKKKKKKKKKKKKKKKKKK.....KK....',
    '...........KKKKKKKKKKKKKKKKKK.....KK....',
    '...........KKKKKKKKKKKKKKKKKKK...KKK....',
    '...........KKKKKKKKKKKKKKKKKKK.KKKK.....',
    '...........KKKKKKKKKKKKKKKKKKKKKKKK.....',
    '...........KKKKKKKKKwKKKKKKKKKKKK.......',
    '...........KKKKKKKKKwKKKKKKKKKK.........',
    '............KKKKKKKKwKKKKKKKK...........',
    '...................KKK..................',
  ] },
};

/* ------------------------------------------------------------------ */
/* Pose → frame sequences                                              */
/* ------------------------------------------------------------------ */

/**
 * `e` suffixes are ear-flick variants: same pose, one ear folded back. Swapping
 * to them for ~150ms is what an ear twitch is, and because it's a whole frame
 * rather than an overlay it can never land half a pixel off.
 *
 * `a` is the attentive head — turned out of profile to face you. It exists ONLY
 * for standing. A walking cat always uses the profile head, because a cat that
 * strolls left while staring at the camera reads as a broken neck, not as
 * friendliness.
 */
export const POSE_FRAMES: Record<string, string[]> = {
  sit: ['sit0', 'sit1'],
  sitEar: ['sit0e', 'sit1e'],
  groom: ['groom0', 'groom1'],
  stand: ['stand0', 'stand1'],
  standEar: ['stand0e', 'stand1e'],
  standAttentive: ['stand0a', 'stand1a'],
  walk: ['walk0', 'walk1', 'walk2', 'walk3'],
  run: ['run0', 'run1', 'run2', 'run3'],
  roll: ['roll0', 'roll1', 'roll2', 'roll3'],
  pounce: ['pounce0', 'pounce1', 'pounce2'],
  paw: ['paw0', 'paw1'],
  sleep: ['sleep0', 'sleep1'],
  stretch: ['stretch0', 'stretch1', 'stretch2'],
  celebrate: ['jump0', 'jump1', 'jump2'],
  scruff: ['scruff0', 'scruff1'],
  startle: ['startle0'],
};

/* ------------------------------------------------------------------ */
/* Compiler — chars to a tinted, outlined, 1px-per-pixel canvas         */
/* ------------------------------------------------------------------ */

export interface Rect { x: number; y: number; w: number; h: number }

export interface CompiledFrame {
  /** ART_W x ART_H canvas, one canvas pixel per art pixel. Pupils excluded. */
  img: HTMLCanvasElement;
  /** art-x of the feet, so a tail sticking out one side doesn't shift the cat */
  anchorX: number;
  /** one per eye, in draw order; pupils are painted at runtime so they can track */
  pupils: Rect[];
  /** eye-white bounding boxes, used to close the lids for a blink */
  eyes: Rect[];
}

const SILHOUETTE = new Set(['K', 'S', 'B', 'E', 'P', 'N', 'I']);

const CHAR_COLOR: Record<string, keyof CoatPalette> = {
  K: 'body', S: 'shade', B: 'belly', E: 'eye', P: 'eye', N: 'nose', I: 'earInner', w: 'detail',
};

/** 8-connected clusters of eye pixels, so left and right eyes stay independent */
function eyeClusters(rows: string[]): { cells: [number, number][] }[] {
  const seen = new Set<string>();
  const out: { cells: [number, number][] }[] = [];
  for (let y = 0; y < ART_H; y++) {
    for (let x = 0; x < ART_W; x++) {
      const ch = rows[y][x];
      if (ch !== 'E' && ch !== 'P') continue;
      const key = `${x},${y}`;
      if (seen.has(key)) continue;
      const cells: [number, number][] = [];
      const stack: [number, number][] = [[x, y]];
      seen.add(key);
      while (stack.length) {
        const [cx, cy] = stack.pop()!;
        cells.push([cx, cy]);
        for (let dy = -1; dy <= 1; dy++) {
          for (let dx = -1; dx <= 1; dx++) {
            const nx = cx + dx, ny = cy + dy;
            if (nx < 0 || nx >= ART_W || ny < 0 || ny >= ART_H) continue;
            const nch = rows[ny][nx];
            if (nch !== 'E' && nch !== 'P') continue;
            const nkey = `${nx},${ny}`;
            if (seen.has(nkey)) continue;
            seen.add(nkey);
            stack.push([nx, ny]);
          }
        }
      }
      out.push({ cells });
    }
  }
  return out;
}

function bbox(cells: [number, number][]): Rect {
  let x0 = Infinity, y0 = Infinity, x1 = -Infinity, y1 = -Infinity;
  for (const [x, y] of cells) {
    if (x < x0) x0 = x; if (x > x1) x1 = x;
    if (y < y0) y0 = y; if (y > y1) y1 = y;
  }
  return { x: x0, y: y0, w: x1 - x0 + 1, h: y1 - y0 + 1 };
}

function compileFrame(art: { anchorX: number; rows: string[] }, pal: CoatPalette): CompiledFrame {
  const cv = document.createElement('canvas');
  cv.width = ART_W;
  cv.height = ART_H;
  const ctx = cv.getContext('2d')!;
  const rows = art.rows;

  // 1. outline first — every transparent pixel touching the silhouette
  ctx.fillStyle = pal.outline;
  for (let y = 0; y < ART_H; y++) {
    for (let x = 0; x < ART_W; x++) {
      if (rows[y][x] !== '.') continue;
      let touching = false;
      for (let dy = -1; dy <= 1 && !touching; dy++) {
        for (let dx = -1; dx <= 1; dx++) {
          const nx = x + dx, ny = y + dy;
          if (nx < 0 || nx >= ART_W || ny < 0 || ny >= ART_H) continue;
          if (SILHOUETTE.has(rows[ny][nx])) { touching = true; break; }
        }
      }
      if (touching) ctx.fillRect(x, y, 1, 1);
    }
  }

  // 2. the cat itself. Pupils are laid down as eye-white; the renderer paints
  //    the real pupil on top wherever the cat happens to be looking.
  for (let y = 0; y < ART_H; y++) {
    for (let x = 0; x < ART_W; x++) {
      const ch = rows[y][x];
      if (ch === '.') continue;
      const key = CHAR_COLOR[ch];
      if (!key) continue;
      ctx.fillStyle = pal[key];
      ctx.fillRect(x, y, 1, 1);
    }
  }

  const clusters = eyeClusters(rows);
  const eyes: Rect[] = [];
  const pupils: Rect[] = [];
  for (const c of clusters) {
    eyes.push(bbox(c.cells));
    const pupilCells = c.cells.filter(([x, y]) => rows[y][x] === 'P');
    if (pupilCells.length) pupils.push(bbox(pupilCells));
  }

  return { img: cv, anchorX: art.anchorX, pupils, eyes };
}

export type Sheet = Record<string, CompiledFrame>;

const sheetCache = new Map<number, Sheet>();

/** Compiled frames for a coat. Baked once, then reused for the session. */
export function getSheet(coatIndex: number): Sheet | null {
  if (typeof document === 'undefined') return null; // SSR — no canvas to bake into
  const i = ((coatIndex % COATS.length) + COATS.length) % COATS.length;
  const cached = sheetCache.get(i);
  if (cached) return cached;
  const pal = COATS[i];
  const sheet: Sheet = {};
  for (const [name, art] of Object.entries(FRAME_ART)) sheet[name] = compileFrame(art, pal);
  sheetCache.set(i, sheet);
  return sheet;
}
