/**
 * The shape catalogue - every stampable glyph, grouped by the kind of thinking
 * it belongs to.
 *
 * It used to be a 214-entry array literal sitting inline in FloatingToolbar's
 * JSX, which is why nothing else could offer a shape picker: the list wasn't a
 * value, it was a chunk of one component's render. The properties rail draws
 * from it now, and the domains below are the tabs it draws.
 */

export type ShapeDomain =
  | 'brainstorm' | 'code' | 'love' | 'usecase' | 'story' | 'system' | 'science' | 'nature' | 'ui';

export interface ShapeOption {
  id: string;
  label: string;
  domain: ShapeDomain;
}

/** Tab order in the picker - 'all' first, then the domains as authored. */
export const SHAPE_DOMAINS: { id: ShapeDomain | 'all'; label: string }[] = [
  { id: 'all', label: 'All' },
  { id: 'brainstorm', label: 'Brainstorm' },
  { id: 'code', label: 'Tech' },
  { id: 'love', label: 'Expressive' },
  { id: 'usecase', label: 'Actions' },
  { id: 'story', label: 'Story' },
  { id: 'system', label: 'System' },
  { id: 'science', label: 'Science' },
  { id: 'nature', label: 'Nature' },
  { id: 'ui', label: 'UI & Layout' },
];

export const SHAPE_CATALOG: ShapeOption[] = [
  // Brainstorm
  { id: 'lightbulb', label: 'Lightbulb', domain: 'brainstorm' },
  { id: 'sticky', label: 'Sticky', domain: 'brainstorm' },
  { id: 'cloud', label: 'Cloud', domain: 'brainstorm' },
  { id: 'star', label: 'Star', domain: 'brainstorm' },
  { id: 'sun', label: 'Sun', domain: 'brainstorm' },
  { id: 'moon', label: 'Moon', domain: 'brainstorm' },
  { id: 'target', label: 'Target', domain: 'brainstorm' },
  { id: 'puzzle', label: 'Puzzle', domain: 'brainstorm' },
  { id: 'gear', label: 'Gear', domain: 'brainstorm' },
  { id: 'funnel', label: 'Funnel', domain: 'brainstorm' },
  { id: 'magnet', label: 'Magnet', domain: 'brainstorm' },
  { id: 'square', label: 'Square', domain: 'brainstorm' },
  { id: 'circle', label: 'Circle', domain: 'brainstorm' },
  { id: 'triangle', label: 'Triangle', domain: 'brainstorm' },
  { id: 'diamond', label: 'Diamond', domain: 'brainstorm' },
  { id: 'octagon', label: 'Stop', domain: 'brainstorm' },
  { id: 'lightbulb-spark', label: 'Idea Spark', domain: 'brainstorm' },
  { id: 'compass', label: 'Compass', domain: 'brainstorm' },
  { id: 'rocket', label: 'Rocket', domain: 'brainstorm' },
  { id: 'radar', label: 'Radar', domain: 'brainstorm' },
  { id: 'prism', label: 'Prism', domain: 'brainstorm' },
  { id: 'light-beam', label: 'Ray', domain: 'brainstorm' },
  { id: 'telescope', label: 'Foresight', domain: 'brainstorm' },
  { id: 'magnifier', label: 'Zoom', domain: 'brainstorm' },
  { id: 'atom-idea', label: 'Idea Atom', domain: 'brainstorm' },
  { id: 'spark-cluster', label: 'Sparks', domain: 'brainstorm' },
  { id: 'anchor', label: 'Anchor', domain: 'brainstorm' },
  { id: 'bridge', label: 'Bridge', domain: 'brainstorm' },

  // Code (Tech)
  { id: 'terminal', label: 'Terminal', domain: 'code' },
  { id: 'brackets', label: 'Brackets', domain: 'code' },
  { id: 'api', label: 'API', domain: 'code' },
  { id: 'server', label: 'Server', domain: 'code' },
  { id: 'cube', label: 'Cube', domain: 'code' },
  { id: 'branch', label: 'Branch', domain: 'code' },
  { id: 'terminal-prompt', label: 'Prompt', domain: 'code' },
  { id: 'cpu', label: 'CPU', domain: 'code' },
  { id: 'globe', label: 'Globe', domain: 'code' },
  { id: 'key', label: 'Key', domain: 'code' },
  { id: 'database', label: 'Database', domain: 'code' },
  { id: 'document', label: 'Doc', domain: 'code' },
  { id: 'folder', label: 'Folder', domain: 'code' },
  { id: 'queue', label: 'Queue', domain: 'code' },
  { id: 'webhook', label: 'Webhook', domain: 'code' },
  { id: 'cache', label: 'Cache', domain: 'code' },
  { id: 'event', label: 'Event', domain: 'code' },
  { id: 'pipeline', label: 'Pipeline', domain: 'code' },
  { id: 'auth', label: 'Auth', domain: 'code' },
  { id: 'diff', label: 'Diff', domain: 'code' },
  { id: 'hash', label: 'Hash', domain: 'code' },
  { id: 'branch-merge', label: 'Git Merge', domain: 'code' },
  { id: 'token', label: 'Token', domain: 'code' },
  { id: 'cpu-chip', label: 'Chip', domain: 'code' },
  { id: 'cloud-download', label: 'Cloud In', domain: 'code' },
  { id: 'cloud-upload', label: 'Cloud Out', domain: 'code' },
  { id: 'git-commit', label: 'Commit', domain: 'code' },
  { id: 'binary', label: 'Binary', domain: 'code' },
  { id: 'cube-stack', label: 'Cube Stack', domain: 'code' },
  { id: 'stack', label: 'Tech Stack', domain: 'code' },
  { id: 'network', label: 'Mesh', domain: 'code' },
  { id: 'data-flow', label: 'Stream', domain: 'code' },
  { id: 'bug', label: 'Bug', domain: 'code' },
  { id: 'terminal-box', label: 'Shell', domain: 'code' },
  { id: 'fingerprint', label: 'Biometric', domain: 'code' },
  { id: 'wifi', label: 'Signal', domain: 'code' },
  { id: 'database-stack', label: 'DB Cluster', domain: 'code' },
  { id: 'ai-spark', label: 'AI Model', domain: 'code' },

  // Love (Expressive)
  { id: 'heart', label: 'Heart', domain: 'love' },
  { id: 'smile', label: 'Smile', domain: 'love' },
  { id: 'thumbs-up', label: 'Up', domain: 'love' },
  { id: 'thumbs-down', label: 'Down', domain: 'love' },
  { id: 'flower', label: 'Flower', domain: 'love' },
  { id: 'sparkles', label: 'Sparkles', domain: 'love' },
  { id: 'trophy', label: 'Trophy', domain: 'love' },
  { id: 'medal', label: 'Medal', domain: 'love' },
  { id: 'gift', label: 'Gift', domain: 'love' },
  { id: 'balloon', label: 'Balloon', domain: 'love' },
  { id: 'clapping', label: 'Clap', domain: 'love' },
  { id: 'coffee', label: 'Coffee', domain: 'love' },
  { id: 'check-circle', label: 'Check', domain: 'love' },
  { id: 'cross-circle', label: 'Cross', domain: 'love' },
  { id: 'fire', label: 'Flame', domain: 'love' },
  { id: 'star-burst', label: 'Supernova', domain: 'love' },
  { id: 'heart-pulse', label: 'Pulse', domain: 'love' },
  { id: 'crown', label: 'Crown', domain: 'love' },
  { id: 'gem', label: 'Jewel', domain: 'love' },
  { id: 'ribbon-award', label: 'Award', domain: 'love' },
  { id: 'peace', label: 'Peace', domain: 'love' },
  { id: 'coffee-cup', label: 'Mug', domain: 'love' },
  { id: 'music-note', label: 'Melody', domain: 'love' },
  { id: 'sunburst', label: 'Radiance', domain: 'love' },
  { id: 'hand-shake', label: 'Pact', domain: 'love' },
  { id: 'party-popper', label: 'Celebrate', domain: 'love' },

  // Usecase (Actions)
  { id: 'speech', label: 'Speech', domain: 'usecase' },
  { id: 'message', label: 'Mail', domain: 'usecase' },
  { id: 'cross', label: 'Cross', domain: 'usecase' },
  { id: 'lightning', label: 'Flash', domain: 'usecase' },
  { id: 'shield', label: 'Shield', domain: 'usecase' },
  { id: 'arrow-left', label: 'Left', domain: 'usecase' },
  { id: 'arrow-right', label: 'Right', domain: 'usecase' },
  { id: 'arrow-up', label: 'Up', domain: 'usecase' },
  { id: 'arrow-down', label: 'Down', domain: 'usecase' },
  { id: 'tag', label: 'Tag', domain: 'usecase' },
  { id: 'banner', label: 'Banner', domain: 'usecase' },
  { id: 'user', label: 'User', domain: 'usecase' },
  { id: 'clock', label: 'Clock', domain: 'usecase' },
  { id: 'calendar', label: 'Calendar', domain: 'usecase' },
  { id: 'card', label: 'Card', domain: 'usecase' },
  { id: 'chart', label: 'Chart', domain: 'usecase' },
  { id: 'cart', label: 'Cart', domain: 'usecase' },
  { id: 'play', label: 'Play', domain: 'usecase' },
  { id: 'pause', label: 'Pause', domain: 'usecase' },
  { id: 'stop', label: 'Stop', domain: 'usecase' },
  { id: 'infinity', label: 'Infinity', domain: 'usecase' },
  { id: 'arrow-up-right', label: 'Trend Up', domain: 'usecase' },
  { id: 'arrow-down-left', label: 'Inflow', domain: 'usecase' },
  { id: 'rotate-cw', label: 'Refresh', domain: 'usecase' },
  { id: 'rotate-ccw', label: 'Undo', domain: 'usecase' },
  { id: 'split', label: 'Split', domain: 'usecase' },
  { id: 'merge', label: 'Join', domain: 'usecase' },
  { id: 'filter-list', label: 'Filter', domain: 'usecase' },
  { id: 'sort', label: 'Sort', domain: 'usecase' },
  { id: 'download', label: 'Download', domain: 'usecase' },
  { id: 'upload', label: 'Upload', domain: 'usecase' },
  { id: 'lock', label: 'Lock', domain: 'usecase' },
  { id: 'unlock', label: 'Unlock', domain: 'usecase' },
  { id: 'eye', label: 'Inspect', domain: 'usecase' },
  { id: 'eye-off', label: 'Hidden', domain: 'usecase' },
  { id: 'layers', label: 'Layers', domain: 'usecase' },

  // Story
  { id: 'beat', label: 'Beat', domain: 'story' },
  { id: 'scene', label: 'Scene', domain: 'story' },
  { id: 'arc', label: 'Arc', domain: 'story' },
  { id: 'twist', label: 'Twist', domain: 'story' },
  { id: 'stakes', label: 'Stakes', domain: 'story' },
  { id: 'character', label: 'Character', domain: 'story' },
  { id: 'whisper', label: 'Whisper', domain: 'story' },
  { id: 'foreshadow', label: 'Foreshadow', domain: 'story' },
  { id: 'world', label: 'World', domain: 'story' },
  { id: 'voice', label: 'Voice', domain: 'story' },
  { id: 'hero-cape', label: 'Protagonist', domain: 'story' },
  { id: 'villain-mask', label: 'Antagonist', domain: 'story' },
  { id: 'climax-peak', label: 'Climax', domain: 'story' },
  { id: 'resolution', label: 'Resolution', domain: 'story' },
  { id: 'sub-plot', label: 'Subplot', domain: 'story' },
  { id: 'theme-core', label: 'Motif', domain: 'story' },
  { id: 'flashback', label: 'Flashback', domain: 'story' },
  { id: 'prop', label: 'Artifact', domain: 'story' },
  { id: 'dialogue-bubble', label: 'Dialogue', domain: 'story' },
  { id: 'scroll-manuscript', label: 'Codex', domain: 'story' },
  { id: 'hourglass', label: 'Tension', domain: 'story' },
  { id: 'keyhole', label: 'Mystery', domain: 'story' },
  { id: 'map-location', label: 'Realm', domain: 'story' },
  { id: 'sword-shield', label: 'Conflict', domain: 'story' },
  { id: 'portal', label: 'Portal', domain: 'story' },

  // System
  { id: 'feedback', label: 'Feedback', domain: 'system' },
  { id: 'bottleneck', label: 'Bottleneck', domain: 'system' },
  { id: 'cascade', label: 'Cascade', domain: 'system' },
  { id: 'threshold', label: 'Threshold', domain: 'system' },
  { id: 'trade-off', label: 'Trade-off', domain: 'system' },
  { id: 'pareto', label: 'Pareto', domain: 'system' },
  { id: 'pivot', label: 'Pivot', domain: 'system' },
  { id: 'lever', label: 'Lever', domain: 'system' },
  { id: 'compound', label: 'Compound', domain: 'system' },
  { id: 'risk', label: 'Risk', domain: 'system' },
  { id: 'feedback-loop', label: 'Circular Loop', domain: 'system' },
  { id: 'balancing-loop', label: 'Balancing B', domain: 'system' },
  { id: 'reinforcing-loop', label: 'Reinforce R', domain: 'system' },
  { id: 'tipping-point', label: 'Tipping Pt', domain: 'system' },
  { id: 'domino', label: 'Domino', domain: 'system' },
  { id: 'equilibrium', label: 'Equilibrium', domain: 'system' },
  { id: 'entropy', label: 'Entropy', domain: 'system' },
  { id: 'synergy', label: 'Synergy', domain: 'system' },
  { id: 'black-box', label: 'Black Box', domain: 'system' },
  { id: 'flywheel', label: 'Flywheel', domain: 'system' },
  { id: 'funnel-filter', label: 'Filter Funnel', domain: 'system' },
  { id: 'friction', label: 'Friction', domain: 'system' },
  { id: 'oscillation', label: 'Oscillation', domain: 'system' },
  { id: 'bottleneck-pipe', label: 'Choke Point', domain: 'system' },
  { id: 'attractor', label: 'Attractor', domain: 'system' },

  // Science (New Category)
  { id: 'dna', label: 'DNA Helix', domain: 'science' },
  { id: 'atom-core', label: 'Quantum Atom', domain: 'science' },
  { id: 'flask', label: 'Flask', domain: 'science' },
  { id: 'molecule', label: 'Molecule', domain: 'science' },
  { id: 'infinity-loop', label: 'Möbius', domain: 'science' },
  { id: 'pi', label: 'Pi Constant', domain: 'science' },
  { id: 'wave-sine', label: 'Sine Wave', domain: 'science' },
  { id: 'delta', label: 'Delta', domain: 'science' },
  { id: 'scale-balance', label: 'Balance Scale', domain: 'science' },
  { id: 'magnet-field', label: 'Mag Field', domain: 'science' },
  { id: 'orbit', label: 'Orbital', domain: 'science' },
  { id: 'sigma', label: 'Sigma Sum', domain: 'science' },

  // Nature (New Category)
  { id: 'leaf', label: 'Eco Leaf', domain: 'nature' },
  { id: 'tree', label: 'Growth Tree', domain: 'nature' },
  { id: 'mountain', label: 'Peak Mountain', domain: 'nature' },
  { id: 'water-drop', label: 'Water Drop', domain: 'nature' },
  { id: 'sun-rays', label: 'Solar Rays', domain: 'nature' },
  { id: 'snowflake', label: 'Snowflake', domain: 'nature' },
  { id: 'planet-ring', label: 'Saturn Planet', domain: 'nature' },
  { id: 'galaxy', label: 'Galaxy Spiral', domain: 'nature' },
  { id: 'comet', label: 'Shooting Star', domain: 'nature' },
  { id: 'volcano', label: 'Eruption', domain: 'nature' },
  { id: 'sprout', label: 'Seedling', domain: 'nature' },
  { id: 'feather', label: 'Feather', domain: 'nature' },

  // UI & Layout (New Category)
  { id: 'layout-grid', label: 'Grid Matrix', domain: 'ui' },
  { id: 'layout-columns', label: 'Columns', domain: 'ui' },
  { id: 'layout-sidebar', label: 'Sidebar', domain: 'ui' },
  { id: 'modal-box', label: 'Modal Dialog', domain: 'ui' },
  { id: 'card-view', label: 'Content Card', domain: 'ui' },
  { id: 'button-primary', label: 'Action Button', domain: 'ui' },
  { id: 'toggle-switch', label: 'Toggle Switch', domain: 'ui' },
  { id: 'slider-control', label: 'Range Slider', domain: 'ui' },
  { id: 'tab-bar', label: 'Nav Tabs', domain: 'ui' },
  { id: 'search-bar', label: 'Search Bar', domain: 'ui' },
  { id: 'avatar-circle', label: 'User Avatar', domain: 'ui' },
  { id: 'image-placeholder', label: 'Media Frame', domain: 'ui' },
];

/** Domain filter + free-text search, in the order the picker wants them. */
export function filterShapes(domain: ShapeDomain | 'all', query: string): ShapeOption[] {
  const q = query.trim().toLowerCase();
  return SHAPE_CATALOG.filter(
    (s) => (domain === 'all' || s.domain === domain) && (!q || s.label.toLowerCase().includes(q) || s.id.includes(q)),
  );
}
